### ISSUE TITLE
Caused by java.lang.RuntimeException: bad array lengths

### ISSUE THREAD

**Issue by jgersindemir** [OneSignal/OneSignal-Unity-SDK#181]
**Description:**

We got too many crash; 
maybe affect sending big picture on push notification

**Environment**

Unity : 2018.2.20f1
Onesignal SDK : 2.7.8
com.android.support.appcompat-v7-27.1.1 ( I found that issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/176 )
Operating System : Android 4 

**Steps to Reproduce Issue:**

We can not reproduce the issue.

**Anything else:**

Caused by java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Caused by java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:827)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
       at android.app.NotificationManager.notify(NotificationManager.java:161)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:207)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:191)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:385)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:106)
       at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:97)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:76)
       at com.onesignal.RestoreJobService.onHandleWork(RestoreJobService.java:46)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:425)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:416)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by rgomezp** [comment]
Hello,
Thanks for your patience. I'm not sure this is related to OneSignal. Could you please elaborate on why you think this is?

**Comment by rgomezp** [comment]
Closing due to inactivity
