### ISSUE TITLE
Android 8.1, 9 Channel Issue. No Channel found for pkg

### ISSUE THREAD

**Issue by DharmikGorsiya** [OneSignal/OneSignal-Unity-SDK#184]
**Description:**

I am using latest SDK of one Signal its working fine below 8.1 version it cause error on 8.1 & 9 So please suggest step to overcome this. also, I have put the logs and, I have modified my original bundle identifier in logs.
(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. Simple step of one signal initiliation
2. also show error while on notification are come.

**Anything else:**

******error in Intilization****** 
```java
 E/NotificationService(1513): No Channel found for pkg=com.demo.demo, channelId=null, id=-1852939072, tag=null, opPkg=com.demo.demo, callingUid=10225, userId=0, incomingUserId=0, notificationUid=10225, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PUBLIC)
```
**Error while push come** (not showing in device)
```java
03-30 10:57:00.805: I/AndroidNative(20846): Push Notification Sended: 
03-30 10:57:00.862: I/AndroidNative(20846): Push Notification Saved
03-30 10:57:00.863: W/System.err(20846): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
03-30 10:57:00.863: W/System.err(20846): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
03-30 10:57:00.863: W/System.err(20846): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
03-30 10:57:00.864: W/System.err(20846): 	at org.json.JSONObject.<init>(JSONObject.java:159)
03-30 10:57:00.866: W/System.err(20846): 	at org.json.JSONObject.<init>(JSONObject.java:176)
03-30 10:57:00.866: W/System.err(20846): 	at com.androidnative.gcm.GcmIntentService.sendNotification(GcmIntentService.java:178)
03-30 10:57:00.866: W/System.err(20846): 	at com.androidnative.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:97)
03-30 10:57:00.866: W/System.err(20846): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
03-30 10:57:00.866: W/System.err(20846): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-30 10:57:00.866: W/System.err(20846): 	at android.os.Looper.loop(Looper.java:193)
03-30 10:57:00.867: W/System.err(20846): 	at android.os.HandlerThread.run(HandlerThread.java:65)
03-30 10:57:00.867: I/AndroidNative(20846): Received: Bundle[{google.delivered_priority=normal, google.sent_time=1553923620856, google.ttl=259200, google.original_priority=normal, custom={"i":"797ec662-cd13-447b-93e3-452c87bfea48"}, oth_chnl=, pri=5, vis=1, from=843007708724, alert=Android 9, title=Test, grp_msg=, google.message_id=0:1553923620862410%d158ca98f9fd7ecd, android.support.content.wakelockid=2}]
03-30 10:57:00.885: I/EventLogChimeraService(18405): Opted in for usage reporting
03-30 10:57:00.886: I/EventLogChimeraService(18405): Aggregate from 1553922304407 (log), 1553922304216 (data)
```

**Comment by jkasten2** [comment]
@DharmikGorsiya The crash is coming from `com.androidnative.gcm.GcmIntentService` which isn't part of OneSignal. I recommend making sure that plugin is updated or if there is a way to turn that part of the plugin off. If you are still seeing the problem I recommend contacting the developer of that plugin to have them check to make sure the payload they are trying to handle is in the correct format.
