### ISSUE TITLE
OneSignal Crash on Android os 4.4

### ISSUE THREAD

**Issue by manlok1992** [OneSignal/OneSignal-Unity-SDK#185]
**Description:**

Hello, I used the Unity OneSignal SDK to build it in Android platform. I received the Crash log in Crashlytics in a few days ago. I do some research here. I saw some people said this issue is trigger in android os 4.4 device. So I double check the crash log that I saw all users are using os 4.4 device. I saw some reference that said enable the multiDex option can resolve it. I already enable it. But I cannot resolve it.

**Environment**

```
defaultConfig {
     targetSdkVersion 26
     applicationId 'com.xxxxx.xxxxxx'
     multiDexEnabled true
     versionCode 41
     versionName "1.0.30"
     minSdkVersion 16
}
```
I am using Unity OneSignal SDK v2.7.8. I think it is the latest SDK. I download the .aar file and put it into the `Assets/Plugins/Android` folder.

**Anything else:**

```
Caused by java.lang.VerifyError: com/onesignal/LocationGMS
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1062)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by manlok1992** [comment]
```
<application android:name="io.fabric.unity.android.MultiDexFabricApplication" />
```
I added already. My apps has multiple application. So I create a class named "MutiDexFabricApplication"

```
public class MultiDexFabricApplication extends FabricApplication {
    public MultiDexFabricApplication() {
    }

    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
}
```

Is it correct?

**Comment by jkasten2** [comment]
@manlok1992 This looks correct, however it might not be loading all the OneSignal classes soon enough. I recommend trying to setup a `multiDexKeepFile` and include all OneSignal classes.
```
-keep class com.onesignal.** { *; } // Keep all OneSignal classes in the main .dex file
```

https://developer.android.com/studio/build/multidex#keep

**Comment by manlok1992** [comment]
Hello @jkasten2, I added the multidexKeepFile and uploaded to play store last week. But I also get the error log in Crashlytics today.

**Comment by jkasten2** [comment]
@manlok1992 No changes in the stacktrace or class name after doing so?
If it is the same class your `multiDexKeepFile` may have not been picked up when building.
To confirm the class is in the main dex you can extract your APK and open the `classes.dex` file with jadx to make sure it is in there.
https://github.com/skylot/jadx

Instead of using multiDex enabling proguard by seeing `minifyEnabled true` might be enough. Enabling this is actually recommend regardless as it makes for a smaller app size.

**Comment by rgomezp** [comment]
Closing due to inactivity
