### ISSUE TITLE
Incompatibility with Firebase 5.7.0

### ISSUE THREAD

**Issue by stopiccot** [OneSignal/OneSignal-Unity-SDK#190]
**Description:**
Seems like OneSignal does not work well with Firebase 5.7.0 on android
Seem to be related to:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/754
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/512

**Environment**
OneSignal Unity SDK 2.7.7
FirebaseAnalytics Unity SDK 5.7.0
Unity 2018.4.0

**Steps to Reproduce Issue:**
App crashes at start sometimes

**Anything else:**

```
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3321)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:106)
```

Any temporary workaround before new sdk version is released?

**Comment by rgomezp** [comment]
@stopiccot ,
It looks like you're actually on an older version of the SDK. Make sure to update it and see if the issue is fixed. Thanks!

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by zenith-jacob** [comment]
Doesn't work with the 2.8.1 either.
Can't you guys just upgrade your SDK to work with the latest Firebase? (18.0.0+)

The SDK is unusable in the current  state.
