### ISSUE TITLE
Missing Support library even after Force Resolve

### ISSUE THREAD

**Issue by imtrobin** [OneSignal/OneSignal-Unity-SDK#222]
Hi, I'm upgraded to 2.8.2 from an old project where onesignal used to work. I'm not sure when and what broke so I created a new ID, and dashboard reports the android support library is missing

I did a Force Resolve successfully and there is no support library

![Image of ](https://filedn.com/l3TGy7Y83c247u0RDYa9fkp/temp/unity3d/onesignal.jpg)

One Signal  2.8.2, Unity 2018.1.4

- Provide a list of your project dependencies. A lot but I think main one is  Stan Assets, which also has a list of android dependencies plugin.

**Comment by imtrobin** [comment]
This is in the Unity logs

Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:cardview-v7:[26.0.0, 27.2.0[ --> androidx.cardview:cardview:1.0.0
com.android.support:customtabs:[26.0.0, 27.2.0[ --> androidx.browser:browser:1.0.0
com.android.support:support-v4:[26.0.0, 27.2.0[ --> androidx.legacy:legacy-support-v4:1.0.0
com.google.android.gms:play-services-base:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-base:12.0.1@aar
com.google.android.gms:play-services-location:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-location:12.0.1@aar
com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[ --> com.google.firebase:firebase-messaging:12.0.1@aar

**Comment by Pankti16** [comment]
I am getting
```
2019-09-16 10:35:12.472 30354-30354/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kyraa.mypiclyricalvideomaker, PID: 30354
    java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.kyraa.mypiclyricalvideomaker-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kyraa.mypiclyricalvideomaker-1/lib/arm64, /data/app/com.kyraa.mypiclyricalvideomaker-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5950)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5539)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5478)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6221)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.kyraa.mypiclyricalvideomaker-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kyraa.mypiclyricalvideomaker-1/lib/arm64, /data/app/com.kyraa.mypiclyricalvideomaker-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5935)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5539) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5478) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
```

**Comment by rgomezp** [comment]
Please take a look at our [Unity troubleshooting guide](https://documentation.onesignal.com/docs/troubleshooting-unity#section-google-play-services-library-missing)

**Comment by imtrobin** [comment]
Have already looked at that, and talking with support

**Comment by Pankti16** [comment]
Okay Thanks

**Comment by areavisuale** [comment]
I have the same problem after updating OneSignal: "Missing Android Support Library"

**Comment by rgomezp** [comment]
@areavisuale , please take a look at the troubleshooting guide linked above

**Comment by areavisuale** [comment]
I followed the guide, it seems a problem related to the new Google Play Service Resolver and Android X compatibility. When I enable Custom Gradle Template in the player settings it gives many errors when I build, referring something like “hex...” I don’t remember... I updated Unity to 2019.2.5 I have the last OneSignal and Firebase Analytics plug-ins, I downloaded the last Platform-Tools, and Android SDK

**Comment by imtrobin** [comment]
I followed the Android X guide, and it works. I'm on U2018.1.8

**Comment by areavisuale** [comment]
If I leave "Custom Gradle Template" unticked in the Player Settings One Signal console says "Missing Android Support Library". If I follow the "Android X" compatibily guide the build fails, with this errors:

![fail](https://user-images.githubusercontent.com/39194720/65411722-e033f580-dded-11e9-945f-8848b3ccd9d1.JPG)

**Comment by areavisuale** [comment]
ok, it seems that the problem was with the maintemplate.gradle file that (I don't know why) had this line:
`classpath 'com.android.tools.build:gradle:3.2.0'`

but my version of Unity used gradle plugin 3.4.1 (gradle version 5.1.1). So I had to change that and now it works

**Comment by rgomezp** [comment]
Glad to hear this has been resolved.
