### ISSUE TITLE
NoSuchMethodError in SDK 2.11 Android

### ISSUE THREAD

**Issue by DanielZ15** [OneSignal/OneSignal-Unity-SDK#254]
Environment:
OneSignal SDK version 2.11.0
Firebase 6.5.0 (Analytics only)
Android platform
Unity 2019.1.7f1

Install OneSignal Unity SDK using instructions below. Follow up to and including step 3. Android Setup.
https://documentation.onesignal.com/docs/unity-sdk-setup

Follow AndroidX troubleshooting guide.

Reproduction steps:
1. Run OneSignal initialization, works fine, user is subscribed and can receive messages.
2. Run OneSignal.Postnotification, following example here:
https://documentation.onesignal.com/docs/sdk-reference#section--postnotification-

Note the below error and failure to post.
Note: This seems to happen with other OneSignal functions as well.
Note: This seems to not happen in the SDK version 2.10.0

AndroidPlayer(ADB@127.0.0.1:34999) AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='postNotification' signature='(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V' in class Ljava.lang.Object;
java.lang.NoSuchMethodError: no non-static method with name='postNotification' signature='(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V' in class Ljava.lang.Object;
	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
  at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJavaImpl.cs:1218 
  at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00005] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJNI.bindings.cs:65 
  at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x0000a] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJavaImpl.cs:1170 
  at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00005] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJNI.bindings.cs:133 
  at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x0001d] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJavaImpl.cs:262 
  at UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) [0x00004] in /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJava.bindings.cs:56 
  at OneSignalAndroid.PostNotification (System.String delegateIdSuccess, System.String delegateIdFailure, System.Collections.Generic.Dictionary`2[TKey,TValue] data) [0x00001] in D:\Unity Projects\PoolGRepo\PoolG\Assets\OneSignal\src\OneSignalAndroid.cs:95 
  at OneSignal.PostNotification (System.Collections.Generic.Dictionary`2[TKey,TValue] data, OneSignal+OnPostNotificationSuccess inOnPostNotificationSuccess, OneSignal+OnPostNotificationFailure inOnPostNotificationFailure) [0x00027] in D:\Unity Projects\PoolGRepo\PoolG\Assets\OneSignal\src\OneSignal.cs:683 
  at OneSignalSender+<TestMethod>d__2.MoveNext () [0x000e1] in D:\Unity Projects\PoolGRepo\PoolG\Assets\Scripts\OneSignalSender.cs:29 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00028] in /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17 
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Export/Android/AndroidJavaImpl.cs Line: 1218)

**Comment by jkasten2** [comment]
Thanks for reporting, this is now fixed in the 2.11.1 release.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.11.1
