### ISSUE TITLE
[CRASH] java.lang.RuntimeException: Unable to instantiate service com.google.firebase.messaging.FirebaseMessagingService: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService

### ISSUE THREAD

**Issue by bilck** [OneSignal/OneSignal-Unity-SDK#267]
**Description:**
When the user first opens the app after a fresh install, everything works perfectly (including notification subscription).
From the 2nd time our app is opened onwards, the app crashes with the following error stack:
`FATAL EXCEPTION: main
Process: com.explot.gouda, PID: 9017
java.lang.RuntimeException: Unable to instantiate service com.google.firebase.messaging.FirebaseMessagingService: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4140)
at android.app.ActivityThread.access$1600(ActivityThread.java:267)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1997)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7762)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4135)
... 8 more
Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.explot.gouda-EHu3C7JJMVwfflwURZioXA==/base.apk)
at com.appsflyer.internal.s.ॱ(:105)
at com.appsflyer.AppsFlyerLibCore.ॱ(:2170)
at com.appsflyer.AppsFlyerLibCore.ॱ(:1950)
at com.appsflyer.AppsFlyerLibCore.ˏ(:1554)
at com.appsflyer.AppsFlyerLibCore.ॱ(:85)
at com.appsflyer.AppsFlyerLibCore$c.run(:3287)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.appsflyer.AFExecutor$4$3.run(:31)
at java.lang.Thread.run(Thread.java:919)`

**Environment**
1. What version of the Unity OneSignal SDK are you using?
OneSignal-Unity-SDK-2.11.2

2. Provide a list of your project dependencies
We have integrated both Firebase Analytics and Firebase Crashlytics to our app.
We also **don't want** to integrate Firebase Messaging on our app, as it is unsupported by Android devices without Google Play. This is **very** important to us.

3. Does the issue occur only in iOS, Android, etc?
Any Android device with Google Play installed. Note that this **doesn't** happen on Kindle Fire devices (at least not on the one we have here).

**Steps to Reproduce Issue:**

  1. Import the latest OneSignalSDK.unitypackage into your project
  2. Initialize OneSignal with app ID
  3. Close app
  4. Reopen app. It will crash.

I have added a report from Crashlytics on this post for more information.
[com.explot.gouda_issue_crash_5E2865BC01DB00016182A693F45F35FD_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/4099762/com.explot.gouda_issue_crash_5E2865BC01DB00016182A693F45F35FD_DNE_0_v2.txt)

**Comment by jkasten2** [comment]
@bilck Thanks for reporting. The crash is happening from the plugin `com.appsflyer.AppsFlyerLibCore`. However `AppsFlyerLibCore` isn't the root cause, it is from a mixture of different Firebase version of it's interdependencies inferred from the `Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible` error.

From a quick look it seems [AppsFlyerSDK's Unity](https://github.com/AppsFlyerSDK/AppsFlyerUnitySampleApp/tree/master/Assets/Plugins/Android/libs) is including static versions of libraries instead of using Google's [unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver) to resolve compatible versions. Doing this will create conflicts with a lot of Unity plugin. I recommend to them to switch to using [AppsFlyerSDK's Unity](https://github.com/AppsFlyerSDK/AppsFlyerUnitySampleApp/tree/master/Assets/Plugins/Android/libs) to resolve their incompatibility issues.

**Comment by bilck** [comment]
Sorry for reporting this issue here, I didn't pay enough attention to the stack trace.

**Comment by AfifAlfahmi** [comment]
i have the same problem and solved it 

plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'kotlin-android'



}
