### ISSUE TITLE
android.os.DeadSystemException crashes on Unity SDK (2.13.1)

### ISSUE THREAD

**Issue by archengineer** [OneSignal/OneSignal-Unity-SDK#316]
Hi,

We are started to see android crash on Firebase Crashlytics after upgrade to the latest one signal sdk. It started to affect our users.

P.S : I see there was an issue about this crash with link -> "https://github.com/OneSignal/OneSignal-Unity-SDK/issues/95".
But it seems this issue not resolved.

Platform: Unity
One Signal Version: 2.13.1
Unity version : 2018.4.25f1
Android OS : 8,9,10
Devices : Samsung, Xiaomi, LGE

Crash Log:
Caused by java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:211)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:177)
       at com.onesignal.OSUtils.packageInstalledAndEnabled(OSUtils.java:287)
       at com.onesignal.OSUtils.isGMSInstalledAndEnabled(OSUtils.java:299)
       at com.onesignal.OSUtils.supportsGooglePush(OSUtils.java:341)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:360)
       at com.onesignal.OSUtils.isAndroidDeviceType(OSUtils.java:382)
       at com.onesignal.LocationController.isGooglePlayServicesAvailable(LocationController.java:286)
       at com.onesignal.LocationController.onFocusChange(LocationController.java:274)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1251)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:263)
       at android.os.Handler.handleCallback(Handler.java:899)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:238)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by andpanda** [comment]
I started to receive this crashes after updating one signal too.

Before I had locationGMS crashes these are gone after the update but now this new crash appeared.

**Comment by andpanda** [comment]
Any news about this issue? This is affecting our production version for months.

**Comment by jkasten2** [comment]
`DeadSystemException` means the app and possibly the core Android system is shutting down so this is very difficult to find the root cause. The stack trace with any `android.os.DeadSystemException` exception is a red herring as this is going to be the last thing your app tried to access from the Android system after the app / system was already in this state.

Since the `DeadSystemException` isn't the root cause it may or may not be a crash that OneSignal is causing. The only option I believe to make progress is to have step by step scenario where the issue can be reproduced. Even if it isn't consistent but can get it fail 1 out of x times this could still be useful.

**Comment by jkasten2** [comment]
We have made a number of internal changes to the Android native part of the SDK in the 3.x.x release. See the 2.x.x migration guide to upgrade:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md

If you continue to see this crash please create a new issue with steps to reproduce. Please link to this issue though for background context.
