### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by nsctnky** [OneSignal/OneSignal-Unity-SDK#358]
Hello, I added oneSignal SDK to our project. However, I am not able to build apk anymore.
I follow those:
https://documentation.onesignal.com/docs/unity-sdk-setup
https://documentation.onesignal.com/docs/troubleshooting-unity

During build process, a pop up appears and it says "A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade"

Environment:
Unity 2020.3.1
OneSignal 2.13.4
Firebase 7.1.0 (crashlytics, analytics, auth)

Build log:

```
> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:OneSignalConfig.plugin:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:OneSignalConfig.plugin:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:OneSignalConfig.plugin:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:OneSignalConfig.plugin:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:OneSignalConfig.plugin:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :unityLibrary:OneSignalConfig.plugin:generateReleaseResValues
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResources
> Task :unityLibrary:OneSignalConfig.plugin:generateReleaseResources
> Task :unityLibrary:generateReleaseBuildConfig
> Task :launcher:generateReleaseBuildConfig
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:prepareLintJar
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseResources
> Task :unityLibrary:OneSignalConfig.plugin:packageReleaseResources
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:OneSignalConfig.plugin:parseReleaseLocalResources
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:OneSignalConfig.plugin:generateReleaseBuildConfig
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:extractDeepLinksRelease
> Task :unityLibrary:OneSignalConfig.plugin:extractDeepLinksRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:parseReleaseLocalResources
> Task :unityLibrary:OneSignalConfig.plugin:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish
> Task :unityLibrary:FirebaseCrashlytics.androidlib:prepareLintJarForPublish
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseShaders
> Task :unityLibrary:OneSignalConfig.plugin:processReleaseManifest
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseShaders
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets
> Task :unityLibrary:generateReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:OneSignalConfig.plugin:mergeReleaseShaders
> Task :unityLibrary:OneSignalConfig.plugin:compileReleaseShaders
> Task :unityLibrary:OneSignalConfig.plugin:generateReleaseAssets
> Task :unityLibrary:OneSignalConfig.plugin:packageReleaseAssets
> Task :unityLibrary:OneSignalConfig.plugin:prepareLintJarForPublish
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease
> Task :unityLibrary:OneSignalConfig.plugin:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibResRelease
> Task :unityLibrary:OneSignalConfig.plugin:bundleLibResRelease
> Task :unityLibrary:OneSignalConfig.plugin:generateReleaseRFile
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseRFile
> Task :unityLibrary:OneSignalConfig.plugin:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:OneSignalConfig.plugin:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:OneSignalConfig.plugin:bundleLibRuntimeRelease
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibCompileRelease
> Task :unityLibrary:OneSignalConfig.plugin:bundleLibCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:FirebaseCrashlytics.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:OneSignalConfig.plugin:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileRelease
> Task :unityLibrary:OneSignalConfig.plugin:mergeReleaseNativeLibs
> Task :unityLibrary:OneSignalConfig.plugin:stripReleaseDebugSymbols
> Task :unityLibrary:OneSignalConfig.plugin:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:bundleLibResRelease
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:generateReleaseRFile

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibCompileRelease
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :launcher:processReleaseManifest
> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders
> Task :launcher:generateReleaseAssets
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:javaPreCompileRelease
> Task :launcher:validateSigningRelease
> Task :launcher:mergeReleaseResources
> Task :launcher:processReleaseResources
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease
> Task :launcher:desugarReleaseFileDependencies

> Task :launcher:mergeExtDexRelease

> Task :launcher:mergeReleaseNativeLibs
> Task :launcher:stripReleaseDebugSymbols
> Task :launcher:mergeExtDexRelease FAILED
> Task :launcher:mergeReleaseJavaResource
108 actionable tasks: 108 executed
```

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Note: /Users/*****/Workstation/******-mobile/Temp/gradleOut/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/*****/Workstation/*****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar: D8: Type bolts.AppLink$Target is defined multiple times: /Users/*****/Workstation/*****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex, /Users/*****/Workstation/******-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_jetified-com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type bolts.AppLink$Target is defined multiple times: /Users/*****/Workstation/*****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex, /Users/*****/Workstation/****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_jetified-com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:445)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.O.a(:65)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	... 34 more
Caused by: com.android.tools.r8.utils.b: Error: /Users/*****/Workstation/*****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex, Type bolts.AppLink$Target is defined multiple times: /Users/****/Workstation/******-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex, /Users/****/Workstation/******-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_jetified-com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex
	at com.android.tools.r8.utils.y0.a(:21)
	at com.android.tools.r8.utils.x0.a(:30)
	at com.android.tools.r8.utils.x0.a(:10)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.x0.a(:6)
	at com.android.tools.r8.graph.A0$c.a(:6)
	at com.android.tools.r8.dex.a.a(:85)
	at com.android.tools.r8.dex.a.a(:12)
	at com.android.tools.r8.D8.d(:6)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.O.a(:30)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeExtDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type bolts.AppLink$Target is defined multiple times: /Users/*****/Workstation/*****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex, /Users/****/Workstation/****-mobile/Temp/gradleOut/launcher/build/intermediates/external_file_lib_dex_archives/release/out/14_jetified-com.parse.bolts.bolts-applinks-1.4.0.jar:classes.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
```

**Comment by justin-pierce** [comment]
Getting same thing -- ever find a resolution?

**Comment by mattlovell** [comment]
im getting this now, using Unity 2021.1.14f1 and latest Onesignal - only way to get my android build completed was to remove onesignal completely.... now its on the OneSignal is on the Asset Store, should we be using that version instead?

**Comment by cihadturhan** [comment]
Assetstore version didn't work either...

**Comment by nvtuan96** [comment]
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
**#android.enableR8=**MINIFY_WITH_R_EIGHT****
unityStreamingAssets=.unity3d**STREAMING_ASSETS**
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**
Open gradleTemplate.properties in comment bold line above. Try it bro

**Comment by nvtuan96** [comment]
![image](https://user-images.githubusercontent.com/47739604/155911471-d8d32031-54bd-4d65-ae88-7bd67b055a74.png)

**Comment by jkasten2** [comment]
@nsctnky The root of the error is the following:
```
Type bolts.AppLink$Target is defined multiple times:
```

OneSignal does not use ` bolts.AppLink` so it doesn't seem related to OneSignal. The OneSignal-Unity-SDK 2.x.x version required a number of `.gradle` settings it no longer needs in the 3.x.x version. Please try out the new version and create a new issue it the build error is still happening. _Include a reference this issue for background context_

Check out the full migration guide for step-by-step on upgrading 2.x.x to 3.x.x:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md
