### ISSUE TITLE
WP81 runtime unhandled exception

### ISSUE THREAD

**Issue by Zubius** [OneSignal/OneSignal-Unity-SDK#36]
My app opens browser for authorization and returns to app via protocol. On return I'm gettin exception
and my app crashes.
OneSignal version 2.2.0 Unity version 5.4.2f2
```CSharp
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue()
  at Newtonsoft.Json.JsonTextReader.ReadInternal()
  at Newtonsoft.Json.JsonTextReader.Read()
  at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
  at Newtonsoft.Json.Linq.JObject.Parse(String json)
  at OneSignalSDK_WP_WNS.OneSignal.checkForNotificationOpened(String args)
  at OneSignalSDK_WP_WNS.OneSignal.OneSignal_V', Sender: '<null>'. Missing try/catch blocks.
```

**Comment by Nightsd01** [comment]
Due to a very small user base, we will no longer be supporting the Windows Phone unity plugin. Apologies for any inconvenience this may cause. We will not be removing it from the SDK but we will not be investing resources into updating it either.
