### ISSUE TITLE
com.google.android.gms:play-services-auth:17.0.0 (no found AdvertisingIdClient)

### ISSUE THREAD

**Issue by Avatarchik** [OneSignal/OneSignal-Unity-SDK#366]
OneSignal 2.3.6
Unity 2021.1.6f1
Android 9

If I am using 

com.google.android.gms:play-services-auth:17.0.0
or com.google.android.gms:play-services-auth-api-phone:17.1.0
I get an error in the log

2021-07-01 22:38:02.708 26903-27255/com.skytechsport.app I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app ONESIGNAL_SDK_FCM_APP_NAME
2021-07-01 22:38:02.754 26903-27255/com.skytechsport.app I/OneSignal: Device registered, push token = *****
2021-07-01 22:38:02.762 26903-27264/com.skytechsport.app I/OneSignal: Error getting Google Ad id: 
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
        at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
        at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1399)
        at com.onesignal.OneSignal.access$1900(OneSignal.java:89)
        at com.onesignal.OneSignal$7.run(OneSignal.java:1381)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.identifier.AdvertisingIdClient" on path: DexPathList[[zip file "/data/app/com.skytechsport.app-4XQPsnxxq1a7FlVLpNTBnA==/base.apk"],nativeLibraryDirectories=[/data/app/com.skytechsport.app-4XQPsnxxq1a7FlVLpNTBnA==/lib/arm64, /data/app/com.skytechsport.app-4XQPsnxxq1a7FlVLpNTBnA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45) 
        at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1399) 
        at com.onesignal.OneSignal.access$1900(OneSignal.java:89) 
        at com.onesignal.OneSignal$7.run(OneSignal.java:1381) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@Avatarchik OneSignal no longer uses the `AdvertisingIdClient` in the 3.x.x version. Please check out or migration guide to get updated to this version.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/main/MIGRATION.md
