### ISSUE TITLE
[Bug]: Runtime crashes on 3.0.2 iOS & Android

### ISSUE THREAD

**Issue by asiepshtain** [OneSignal/OneSignal-Unity-SDK#518]
### What happened?

Upgraded from 2.14.6 to 3.0.2 
QA went fine, once released saw a marked increase in crashes on both ios and android

### Steps to reproduce?

```Markdown
1. build an app with OneSignal 3.0.2 on Unity 2019.4.28f1 using Gradle 5.6.4
2. release it
3. look at firebase for errors
```

### What did you expect to happen?

I expected not to see new crashes

### Unity version

2019.4.28f1 using Gradle 5.6.4

### OneSignal Unity SDK version

3.0.2

### Platform

iOS, Android

### Relevant log output

```Shell
IOS firebase error:

OneSignal
-[OneSignalAppDelegate oneSignalApplicationWillTerminate:]
Crashed: com.apple.main-thread
0  UnityFramework                 0xc16eec operator delete[](void*, std::nothrow_t const&) + 59276
1  UnityFramework                 0xc16e1c operator delete[](void*, std::nothrow_t const&) + 59068
2  UnityFramework                 0xd75ca8 operator delete[](void*, std::nothrow_t const&) + 1496392
3  UnityFramework                 0xd760c0 operator delete[](void*, std::nothrow_t const&) + 1497440
4  UnityFramework                 0xd82ca4 operator delete[](void*, std::nothrow_t const&) + 1549636
5  UnityFramework                 0x106a1c4 MetalHeap::AliasResources() + 139696
6  UnityFramework                 0x14478 (Missing UUID 358f976b69a6399f989bbae30434ecc5)
7  OneSignal                      0x3d130 -[OneSignalAppDelegate oneSignalApplicationWillTerminate:] + 144
8  UIKitCore                      0xe97320 -[UIApplication _terminateWithStatus:] + 240
9  UIKitCore                      0x5fbb64 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
10 UIKitCore                      0x7d6250 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
11 UIKitCore                      0xe93950 -[UIApplication workspaceShouldExit:withTransitionContext:] + 220
12 FrontBoardServices             0x48f20 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 76
13 FrontBoardServices             0x9bdc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
14 FrontBoardServices             0x48ebc __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 104
15 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
16 libdispatch.dylib              0x7150 _dispatch_block_invoke_direct$VARIANT$mp + 220
17 FrontBoardServices             0xb2ac __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
18 FrontBoardServices             0xa7c0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
19 FrontBoardServices             0xe960 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
20 CoreFoundation                 0xb34ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
21 CoreFoundation                 0xc361c __CFRunLoopDoSource0 + 204
22 CoreFoundation                 0x5824 __CFRunLoopDoSources0 + 256
23 CoreFoundation                 0xaef8 __CFRunLoopRun + 768
24 CoreFoundation                 0x1e240 CFRunLoopRunSpecific + 572
25 GraphicsServices               0x1988 GSEventRunModal + 160
26 UIKitCore                      0x4e541c -[UIApplication _run] + 1080
27 UIKitCore                      0x27eb88 UIApplicationMain + 336
28 UnityFramework                 0x18504 (Missing UUID 358f976b69a6399f989bbae30434ecc5)
29 RummyStars                     0x7e00 main + 28 (main.mm:28)
30 ???                            0x100d7c3d0 (Missing)


Android firebase error:
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.bbumgames.rummystars/com.facebook.ads.AudienceNetworkActivity}: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4397)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4429)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7684)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Caused by java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
       at androidx.work.WorkManager.getInstance(WorkManager.java:184)
       at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager.java:48)
       at com.onesignal.OneSignal.onAppFocusLogic(OneSignal.java:1432)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1413)
       at com.onesignal.OSFocusHandler.startOnFocusWork(OSFocusHandler.kt:49)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:191)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:95)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:91)
       at android.app.Application.dispatchActivityResumed(Application.java:436)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1265)
       at android.app.Activity.onResume(Activity.java:1792)
       at com.facebook.ads.AudienceNetworkActivity.access$301(AudienceNetworkActivity.java:26)
       at com.facebook.ads.AudienceNetworkActivity$1.onResume(AudienceNetworkActivity.java:48)
       at com.facebook.ads.redexgen.X.5A.onResume(:13568)
       at com.facebook.ads.AudienceNetworkActivity.onResume(AudienceNetworkActivity.java:107)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
       at android.app.Activity.performResume(Activity.java:7942)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4384)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4429)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7684)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

Also on Andorid Firebase

Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.bbumgames.rummystars/com.unity3d.player.UnityPlayerActivity}: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5557)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5460)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Caused by java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
       at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
       at androidx.work.WorkManager.getInstance(WorkManager.java:184)
       at com.onesignal.OSFocusHandler.startOnLostFocusWorker(OSFocusHandler.kt:85)
       at com.onesignal.ActivityLifecycleHandler.handleLostFocus(ActivityLifecycleHandler.java:183)
       at com.onesignal.ActivityLifecycleHandler.onActivityPaused(ActivityLifecycleHandler.java:102)
       at com.onesignal.ActivityLifecycleListener.onActivityPaused(ActivityLifecycleListener.java:97)
       at android.app.Application.dispatchActivityPaused(Application.java:465)
       at android.app.Activity.dispatchActivityPaused(Activity.java:1473)
       at android.app.Activity.onPause(Activity.java:2426)
       at com.unity3d.player.UnityPlayerActivity.onPause(UnityPlayerActivity.java:76)
       at android.app.Activity.performPause(Activity.java:8485)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5547)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5460)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@asiepshtain Thanks for reporting with the full stack traces.
### IOS
```
-[OneSignalAppDelegate oneSignalApplicationWillTerminate:]
Crashed: com.apple.main-thread
0  UnityFramework                 0xc16eec operator delete[](void*, std::nothrow_t const&) + 59276
1  UnityFramework                 0xc16e1c operator delete[](void*, std::nothrow_t const&) + 59068
2  UnityFramework                 0xd75ca8 operator delete[](void*, std::nothrow_t const&) + 1496392
3  UnityFramework                 0xd760c0 operator delete[](void*, std::nothrow_t const&) + 1497440
4  UnityFramework                 0xd82ca4 operator delete[](void*, std::nothrow_t const&) + 1549636
5  UnityFramework                 0x106a1c4 MetalHeap::AliasResources() + 139696
6  UnityFramework                 0x14478 (Missing UUID 358f976b69a6399f989bbae30434ecc5)
7  OneSignal                      0x3d130 -[OneSignalAppDelegate oneSignalApplicationWillTerminate:] + 144
8  UIKitCore                      0xe97320 -[UIApplication _terminateWithStatus:] + 240
```
This crash looks to be when your app is being closed, it isn't clear if the exact reason why the app is closing however
Could you let us know which iOS versions you are seeing this crash on? Also how many reports of this issue are you seeing?

### Android
```
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider
```
This is an issue Google's AndroidX library with OneSignal uses. We are the process of collecting more information and reporting this to Google.

**Comment by asiepshtain** [comment]
**IOS**

This crash occurred on iOS 13.7.0 <> 15.6.0
 on both iPhone and  iPads, there were around 300 crashes over a weekend

**Android**

Is there a known workaround?

**Comment by AlvaroVasconcelos** [comment]
same erro

**Comment by hugolone** [comment]
same here, wait for news.

**Comment by shefich** [comment]
Steps to reproduce:
1. Launch the app.
2. Close the app.
3. Launch it one more time(immidiately).
4. Crash happens.

**Comment by muhammedrollic** [comment]
Hello,

I opened a different [issue](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/563) two days ago. But it seems it is relative with this issue so I want to share my crash information here. We are using Unity SDK 3.0.5 (so the game has iOS SDK 3.11.5). 

When this crash occures, almost all the devices have very low memory (under 100 MB). And generally during the long time spent in game. Also all crashes occur in background.

Here is the stacktraces:

### Stacktrace 1:

```
OneSignalCore
+[SwizzlingForwarder callSelector:onObject:withArgs:]
com.apple.main-thread
0  libsystem_kernel.dylib         0x2138 __ulock_wait + 8
1  libsystem_pthread.dylib        0x3b88 _pthread_join + 444
2  UnityFramework                 0x1b44dc0 PlatformThread::Join(Thread const*) + 131 (PlatformThread.cpp:131)
3  UnityFramework                 0x1b43144 Thread::WaitForExit(bool) + 145 (Thread.cpp:145)
4  UnityFramework                 0x1a8a1d4 JobQueue::Shutdown(JobQueue::ShutdownMode) + 281 (JobQueue.cpp:281)
5  UnityFramework                 0x1ac6570 PlayerCleanup(bool) + 611 (Player.cpp:611)
6  UnityFramework                 0x1ed3be0 UnityCleanup + 220 (LibEntryPoint.mm:220)
7  UnityFramework                 0x157e0 -[UnityAppController applicationWillTerminate:] + 520 (UnityAppController.mm:520)
8  CoreFoundation                 0x21b24 __invoking___ + 148
9  CoreFoundation                 0x3f610 -[NSInvocation invoke] + 468
10 OneSignalCore                  0x4970 +[SwizzlingForwarder callSelector:onObject:withArgs:] + 312
11 OneSignal                      0x2ef60 -[OneSignalAppDelegate oneSignalApplicationWillTerminate:] + 256
12 UIKitCore                      0xf5bdac -[UIApplication _terminateWithStatus:] + 244
13 UIKitCore                      0x6369d4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x82c834 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf58128 -[UIApplication workspaceShouldExit:withTransitionContext:] + 224
16 FrontBoardServices             0x4efec __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa308 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4ef84 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
20 libdispatch.dylib              0x74e0 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xbc70 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xb040 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf700 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcc1a0 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x5694 __CFRunLoopDoSources0 + 268
27 CoreFoundation                 0xb05c __CFRunLoopRun + 828
28 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x1374 GSEventRunModal + 164
30 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
31 UIKitCore                      0x296090 UIApplicationMain + 364
32 UnityFramework                 0x19850 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 96 (main.mm:96)
33 <App name>                         0x7e00 main + 28 (main.mm:28)
34 ???                            0x10015dda4 (Missing)
```

### Stacktrace 2:

```
OneSignalCore
+[SwizzlingForwarder callSelector:onObject:withArgs:]
EX_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000038

Crashed: com.apple.main-thread
0  libsystem_malloc.dylib         0x537c tiny_free_list_add_ptr + 360
1  libsystem_malloc.dylib         0x4378 tiny_free_no_lock + 564
2  libsystem_malloc.dylib         0x50dc free_tiny + 356
3  UnityFramework                 0x1926470 BaseAllocator::TryDeallocate(void*) + 50 (BaseAllocator.cpp:50)
4  UnityFramework                 0x1922efc MemoryManager::Deallocate(void*, MemLabelId, char const*, int) + 1912 (MemoryManager.cpp:1912)
5  UnityFramework                 0x1922e64 operator delete(void*) + 276 (MemoryManager.cpp:276)
6  UnityFramework                 0x23976e8 std::__1::__list_imp<il2cpp::utils::MemoryPool::Region*, std::__1::allocator<il2cpp::utils::MemoryPool::Region*> >::clear() + 234 (new:234)
7  UnityFramework                 0x23972b0 il2cpp::utils::MemoryPool::~MemoryPool() + 712 (list:712)
8  UnityFramework                 0x23aa9b8 il2cpp::vm::MetadataAllocCleanup() + 31 (MetadataAlloc.cpp:31)
9  UnityFramework                 0x23ba124 il2cpp::vm::Runtime::Shutdown() + 414 (Runtime.cpp:414)
10 UnityFramework                 0x1bb4cb0 CleanupIl2Cpp() + 296 (MonoManager_Il2Cpp.cpp:296)
11 UnityFramework                 0x1ac6580 PlayerCleanup(bool) + 627 (Player.cpp:627)
12 UnityFramework                 0x1ed3be0 UnityCleanup + 220 (LibEntryPoint.mm:220)
13 UnityFramework                 0x157e0 -[UnityAppController applicationWillTerminate:] + 520 (UnityAppController.mm:520)
14 CoreFoundation                 0x20dd0 __invoking___ + 144
15 CoreFoundation                 0x3cea8 -[NSInvocation invoke] + 300
16 OneSignalCore                  0x4970 +[SwizzlingForwarder callSelector:onObject:withArgs:] + 312
17 OneSignal                      0x2ef60 -[OneSignalAppDelegate oneSignalApplicationWillTerminate:] + 256
18 UIKitCore                      0xe985f8 -[UIApplication _terminateWithStatus:] + 240
19 UIKitCore                      0x5fc1d4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 124
20 UIKitCore                      0x7d6bf0 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
21 UIKitCore                      0xe94c28 -[UIApplication workspaceShouldExit:withTransitionContext:] + 220
22 FrontBoardServices             0x48f20 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 76
23 FrontBoardServices             0x9bdc -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 232
24 FrontBoardServices             0x48ebc __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 104
25 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
26 libdispatch.dylib              0x7150 _dispatch_block_invoke_direct$VARIANT$mp + 220
27 FrontBoardServices             0xb2ac __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 40
28 FrontBoardServices             0xa7c0 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 176
29 FrontBoardServices             0xe960 -[FBSSerialQueue _performNextFromRunLoopSource] + 24
30 CoreFoundation                 0xb34fc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
31 CoreFoundation                 0xc362c __CFRunLoopDoSource0 + 204
32 CoreFoundation                 0x5834 __CFRunLoopDoSources0 + 256
33 CoreFoundation                 0xaf08 __CFRunLoopRun + 768
34 CoreFoundation                 0x1e250 CFRunLoopRunSpecific + 572
35 GraphicsServices               0x1988 GSEventRunModal + 160
36 UIKitCore                      0x4e5a94 -[UIApplication _run] + 1080
37 UIKitCore                      0x27efd4 UIApplicationMain + 336
38 UnityFramework                 0x19850 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 96 (main.mm:96)
39 Onnect                         0x7e00 main + 28 (main.mm:28)
40 ???                            0x1026044d0 (Missing)
```

**Comment by muhammedrollic** [comment]
Hello everyone,

Is there any update for this issue?

**Comment by vfilho** [comment]
I'm seeing the exactly same issue, what is the status? When will you release the proper fix for this issue?

**Comment by nan-li** [comment]
Hi all, apologies this issue has gone stale; the team is no longer actively supporting and patching the v3 major version of this SDK.

I recommend to upgrade to v5 of our SDK. Please let us know if we can help you with the transition.
