### ISSUE TITLE
Latest version cannot build for iOS on a mac

### ISSUE THREAD

**Issue by joaquingrech** [OneSignal/OneSignal-Unity-SDK#525]
It was working fine. I updated to the latest 3.0.3 package and now it won't compile on iOS with he following error. This is using Unity 2021.3.6f

iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and failed. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In Podfile:
    OneSignalXCFramework (= 3.11.2)

None of your spec sources contain a spec satisfying the dependency: `OneSignalXCFramework (= 3.11.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

pod repo update output:

Updating spec repo `master`
  $ /usr/bin/git -C /Users/Joaquin/.cocoapods/repos/master fetch origin --progress
  $ /usr/bin/git -C /Users/Joaquin/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/Joaquin/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 23773a4b93e6 [Add] WordPressKit 4.56.0
Updating spec repo `trunk`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.4 (21F79)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 23773a4b93e67f05418be076373f19163515ce63

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'OneSignalXCFramework', '3.11.2'
end
target 'Unity-iPhone' do
  pod 'OneSignalXCFramework', '3.11.2'
end
use_frameworks! :linkage => :static
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '3.11.2'
end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64e%27%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...

  remote: Enumerating objects: 189, done.        
  remote: Counting objects:   0% (1/189)        
  remote: Counting objects:   1% (2/189)        
  remote: Counting objects:   2% (4/189)        
  remote: Counting objects:   3% (6/189)        
  remote: Counting objects:   4% (8/189)        
  remote: Counting objects:   5% (10/189)        
  remote: Counting objects:   6% (12/189)        
  remote: Counting objects:   7% (14/189)        
  remote: Counting objects:   8% (16/189)        
  remote: Counting objects:   9% (18/189)        
  remote: Counting objects:  10% (19/189)        
  remote: Counting objects:  11% (21/189)        
  remote: Counting objects:  12% (23/189)        
  remote: Counting objects:  13% (25/189)        
  remote: Counting objects:  14% (27/189)        
  remote: Counting objects:  15% (29/189)        
  remote: Counting objects:  16% (31/189)        
  remote: Counting objects:  17% (33/189)        
  remote: Counting objects:  18% (35/189)        
  remote: Counting objects:  19% (36/189)        
  remote: Counting objects:  20% (38/189)        
  remote: Counting objects:  21% (40/189)        
  remote: Counting objects:  22% (42/189)        
  remote: Counting objects:  23% (44/189)        
  remote: Counting objects:  24% (46/189)        
  remote: Counting objects:  25% (48/189)        
  remote: Counting objects:  26% (50/189)        
  remote: Counting objects:  27% (52/189)        
  remote: Counting objects:  28% (53/189)        
  remote: Counting objects:  29% (55/189)        
  remote: Counting objects:  30% (57/189)        
  remote: Counting objects:  31% (59/189)        
  remote: Counting objects:  32% (61/189)        
  remote: Counting objects:  33% (63/189)        
  remote: Counting objects:  34% (65/189)        
  remote: Counting objects:  35% (67/189)        
  remote: Counting objects:  36% (69/189)        
  remote: Counting objects:  37% (70/189)        
  remote: Counting objects:  38% (72/189)        
  remote: Counting objects:  39% (74/189)        
  remote: Counting objects:  40% (76/189)        
  remote: Counting objects:  41% (78/189)        
  remote: Counting objects:  42% (80/189)        
  remote: Counting objects:  43% (82/189)        
  remote: Counting objects:  44% (84/189)        
  remote: Counting objects:  45% (86/189)        
  remote: Counting objects:  46% (87/189)        
  remote: Counting objects:  47% (89/189)        
  remote: Counting objects:  48% (91/189)        
  remote: Counting objects:  49% (93/189)        
  remote: Counting objects:  50% (95/189)        
  remote: Counting objects:  51% (97/189)        
  remote: Counting objects:  52% (99/189)        
  remote: Counting objects:  53% (101/189)        
  remote: Counting objects:  54% (103/189)        
  remote: Counting objects:  55% (104/189)        
  remote: Counting objects:  56% (106/189)        
  remote: Counting objects:  57% (108/189)        
  remote: Counting objects:  58% (110/189)        
  remote: Counting objects:  59% (112/189)        
  remote: Counting objects:  60% (114/189)        
  remote: Counting objects:  61% (116/189)        
  remote: Counting objects:  62% (118/189)        
  remote: Counting objects:  63% (120/189)        
  remote: Counting objects:  64% (121/189)        
  remote: Counting objects:  65% (123/189)        
  remote: Counting objects:  66% (125/189)        
  remote: Counting objects:  67% (127/189)        
  remote: Counting objects:  68% (129/189)        
  remote: Counting objects:  69% (131/189)        
  remote: Counting objects:  70% (133/189)        
  remote: Counting objects:  71% (135/189)        
  remote: Counting objects:  72% (137/189)        
  remote: Counting objects:  73% (138/189)        
  remote: Counting objects:  74% (140/189)        
  remote: Counting objects:  75% (142/189)        
  remote: Counting objects:  76% (144/189)        
  remote: Counting objects:  77% (146/189)        
  remote: Counting objects:  78% (148/189)        
  remote: Counting objects:  79% (150/189)        
  remote: Counting objects:  80% (152/189)        
  remote: Counting objects:  81% (154/189)        
  remote: Counting objects:  82% (155/189)        
  remote: Counting objects:  83% (157/189)        
  remote: Counting objects:  84% (159/189)        
  remote: Counting objects:  85% (161/189)        
  remote: Counting objects:  86% (163/189)        
  remote: Counting objects:  87% (165/189)        
  remote: Counting objects:  88% (167/189)        
  remote: Counting objects:  89% (169/189)        
  remote: Counting objects:  90% (171/189)        
  remote: Counting objects:  91% (172/189)        
  remote: Counting objects:  92% (174/189)        
  remote: Counting objects:  93% (176/189)        
  remote: Counting objects:  94% (178/189)        
  remote: Counting objects:  95% (180/189)        
  remote: Counting objects:  96% (182/189)        
  remote: Counting objects:  97% (184/189)        
  remote: Counting objects:  98% (186/189)        
  remote: Counting objects:  99% (188/189)        
  remote: Counting objects: 100% (189/189)        
  remote: Counting objects: 100% (189/189), done.        
  remote: Compressing objects:   0% (1/136)        
  remote: Compressing objects:   1% (2/136)        
  remote: Compressing objects:   2% (3/136)        
  remote: Compressing objects:   3% (5/136)        
  remote: Compressing objects:   4% (6/136)        
  remote: Compressing objects:   5% (7/136)        
  remote: Compressing objects:   6% (9/136)        
  remote: Compressing objects:   7% (10/136)        
  remote: Compressing objects:   8% (11/136)        
  remote: Compressing objects:   9% (13/136)        
  remote: Compressing objects:  10% (14/136)        
  remote: Compressing objects:  11% (15/136)        
  remote: Compressing objects:  12% (17/136)        
  remote: Compressing objects:  13% (18/136)        
  remote: Compressing objects:  14% (20/136)        
  remote: Compressing objects:  15% (21/136)        
  remote: Compressing objects:  16% (22/136)        
  remote: Compressing objects:  17% (24/136)        
  remote: Compressing objects:  18% (25/136)        
  remote: Compressing objects:  19% (26/136)        
  remote: Compressing objects:  20% (28/136)        
  remote: Compressing objects:  21% (29/136)        
  remote: Compressing objects:  22% (30/136)        
  remote: Compressing objects:  23% (32/136)        
  remote: Compressing objects:  24% (33/136)        
  remote: Compressing objects:  25% (34/136)        
  remote: Compressing objects:  26% (36/136)        
  remote: Compressing objects:  27% (37/136)        
  remote: Compressing objects:  28% (39/136)        
  remote: Compressing objects:  29% (40/136)        
  remote: Compressing objects:  30% (41/136)        
  remote: Compressing objects:  31% (43/136)        
  remote: Compressing objects:  32% (44/136)        
  remote: Compressing objects:  33% (45/136)        
  remote: Compressing objects:  34% (47/136)        
  remote: Compressing objects:  35% (48/136)        
  remote: Compressing objects:  36% (49/136)        
  remote: Compressing objects:  37% (51/136)        
  remote: Compressing objects:  38% (52/136)        
  remote: Compressing objects:  39% (54/136)        
  remote: Compressing objects:  40% (55/136)        
  remote: Compressing objects:  41% (56/136)        
  remote: Compressing objects:  42% (58/136)        
  remote: Compressing objects:  43% (59/136)        
  remote: Compressing objects:  44% (60/136)        
  remote: Compressing objects:  45% (62/136)        
  remote: Compressing objects:  46% (63/136)        
  remote: Compressing objects:  47% (64/136)        
  remote: Compressing objects:  48% (66/136)        
  remote: Compressing objects:  49% (67/136)        
  remote: Compressing objects:  50% (68/136)        
  remote: Compressing objects:  51% (70/136)        
  remote: Compressing objects:  52% (71/136)        
  remote: Compressing objects:  53% (73/136)        
  remote: Compressing objects:  54% (74/136)        
  remote: Compressing objects:  55% (75/136)        
  remote: Compressing objects:  56% (77/136)        
  remote: Compressing objects:  57% (78/136)        
  remote: Compressing objects:  58% (79/136)        
  remote: Compressing objects:  59% (81/136)        
  remote: Compressing objects:  60% (82/136)        
  remote: Compressing objects:  61% (83/136)        
  remote: Compressing objects:  62% (85/136)        
  remote: Compressing objects:  63% (86/136)        
  remote: Compressing objects:  64% (88/136)        
  remote: Compressing objects:  65% (89/136)        
  remote: Compressing objects:  66% (90/136)        
  remote: Compressing objects:  67% (92/136)        
  remote: Compressing objects:  68% (93/136)        
  remote: Compressing ob<message truncated>

**Comment by joaquingrech** [comment]
btw i tried the repo update line as instructed and it fails, also the pod seems to be the latest version installed.
Anything changed on versions between 3.0.2 and 3.0.3 ?

**Comment by jkasten2** [comment]
Closing this issue as stale, please open a new issue if this problem still occurs.
