### ISSUE TITLE
Android 4.4 crash

### ISSUE THREAD

**Issue by bigmack11011** [OneSignal/OneSignal-Unity-SDK#55]
Application crashes on kit-kat when receiving push

`07-10 12:09:37.264 6162-6885/com.kobro.kobro E/AndroidRuntime: FATAL EXCEPTION: IntentService[GcmIntentService]
                                                               Process: com.kobro.kobro, PID: 6162
                                                               java.lang.Error: FATAL EXCEPTION [IntentService[GcmIntentService]]
                                                               Unity version     : 5.6.0f3
                                                               Device model      : ZTE ZTE Blade Q Lux
                                                               Device fingerprint: ZTE/P632A10/P632A10:4.4.2/KOT49H/20150324.102504:user/release-keys
                                                               
                                                               Caused by: java.lang.NullPointerException: println needs a message
                                                                   at android.util.Log.println_native(Native Method)
                                                                   at android.util.Log.d(Log.java:139)
                                                                   at com.androidnative.gcm.GcmIntentService.sendNotification(GcmIntentService.java:295)
                                                                   at com.androidnative.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:97)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                   at android.os.Looper.loop(Looper.java:193)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
`

**Comment by jkasten2** [comment]
@bigmack11011 The crash seems to be triggered by another plugin `com.androidnative`. Did the crash happen when sending a notification from OneSignal or through another system?

If this crash happened when sending a notification from OneSignal make sure you are using the latest OneSignal 2.3.3 SDK in your app.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases
We attempt to prevent the OneSignal payload GCM / FCM from being sent to other Android Receivers in your app. They can create duplicated notification or the other receiver to crash if it doesn't contain error handling. If you have the latest version of the OneSignal SDK then can you provide a link to the other plugin and it's version number?

**Comment by bigmack11011** [comment]
@jkasten2 No, we don't use any other plugins, connected with GCM/FCM, but we've been using Amazon SNS. We've removed it from our project in favor of OneSignal. Triple checked - no files of Amazon SNS and no fields in manifest left in project

**Comment by bigmack11011** [comment]
@jkasten2 Ah, excuse me. We use Ultimate Mobile by Stans's Assets. https://www.assetstore.unity3d.com/en/#!/content/20152

**Comment by Alamgir** [comment]
@bigmack11011 have you tried removing the manifest-declared `GcmIntentService` that is included with the Stan's Assets Unity plugin? 

Reading their documentation here: https://unionassets.com/android-native-plugin/apis-and-requirements-192#push-notifications-api
it appears that the docs tell you to add a receiver for the `com.google.android.c2dm.intent.RECEIVE` intent - try omitting this receiver to see if that allieviates the conflict you're seeing

**Comment by bigmack11011** [comment]
@Alamgir Oh god, yes, it helped, thank you!
