### ISSUE TITLE
[Bug]: Amazon + oneSignal crash on start 

### ISSUE THREAD

**Issue by Vladeng** [OneSignal/OneSignal-Unity-SDK#561]
### What happened?

We have a problem with Amazon version of our game with an integrated onesignal.

### Steps to reproduce?

```Markdown
We did all like an instruction 
https://documentation.onesignal.com/docs/unity-sdk-setup
and
place api_key.txt on Assets/Plugins/Android/ AND Assets/StreamingAssets
our apk: https://www.dropbox.com/s/1n6wqafe058pqv4/do.apk?dl=0

and got crash on start:

Caused by java.lang.RuntimeException: Unable to start receiver com.onesignal.ADMMessageHandler$Receiver: java.lang.IllegalArgumentException: No such service ComponentInfo{com.miniit.difference/com.onesignal.ADMMessageHandlerJob}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3422)
       at android.app.ActivityThread.access$1300(ActivityThread.java:207)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:6752)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)



Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{com.miniit.difference/com.onesignal.ADMMessageHandlerJob}
       at android.os.Parcel.createException(Parcel.java:1954)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:215)
       at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:53)
       at com.amazon.device.messaging.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:361)
       at com.amazon.device.messaging.JobIntentService.enqueueWork(JobIntentService.java:565)
       at com.amazon.device.messaging.ADMMessageReceiver.onReceive(ADMMessageReceiver.java:115)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3413)
       at android.app.ActivityThread.access$1300(ActivityThread.java:207)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:6752)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


I googled it, and it looks like file api_key.txt can't be found but if we look in to apk we can find it on the right place.
```

### What did you expect to happen?

it must work

### Unity version

2020.3.41f1

### OneSignal Unity SDK version

3.0.4

### Platform

Android, Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Apologies this issue is stale, please open a new issue with updated details if this is still relevant today.
