### ISSUE TITLE
[Bug]: Application crashes on first launch on android

### ISSUE THREAD

**Issue by Arikaton** [OneSignal/OneSignal-Unity-SDK#597]
### What happened?

I created empty Unity project (2020.3.38f) and install OneSignal SDK. There is two cases:
1. On device with android 13 it crashes at very first app launch. 
2. On android 12 device OneSignal SDK throw `java.lang.NullPointerException` during initialization

In the first case, you can see the same exception in the general logs of the device after an application failure

### Steps to reproduce?

```Markdown
For my device Samsung SM-A525F/DS with Android 13
1. Install OneSignal Unity SDK v3.0.x
2. Initialize OneSignal at Start() method
3. See app crashes on first launch
4. No exception logs appears in logcat

For other device with Android 12
1. Install OneSignal Unity SDK v3.0.x
2. Initialize OneSignal at Start() method
3. Observe exceptions in logcat.
```

### What did you expect to happen?

No any exceptions or crashes during OneSignal initialization

### Unity version

2020.3.38f

### OneSignal Unity SDK version

3.0.0 - 3.0.9

### Platform

Android

### Relevant log output

```Shell
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper Work [ 
id=8f3e87d2-441c-4b59-873b-d0744abe022e, tags={ FOCUS_LOST_WORKER_TAG, 
com.onesignal.OSFocusHandler$OnLostFocusWorker } ] failed because it threw 
an exception/error
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 
java.util.concurrent.ExecutionException: java.lang.NullPointerException: 
Attempt to invoke virtual method 'android.content.pm.PackageManager 
android.content.Context.getPackageManager()' on a null object reference
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
java.lang.Thread.run(Thread.java:1012)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper Caused by: 
java.lang.NullPointerException: Attempt to invoke virtual method 
'android.content.pm.PackageManager 
android.content.Context.getPackageManager()' on a null object reference
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSUtils.packageInstalledAndEnabled(OSUtils.java:275)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSUtils.isGMSInstalledAndEnabled(OSUtils.java:288)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSUtils.supportsGooglePush(OSUtils.java:330)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSUtils.isAndroidDeviceType(OSUtils.java:371)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.LocationController.isGooglePlayServicesAvailable(LocationController.java:337)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.LocationController.onFocusChange(LocationController.java:325)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1352)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSFocusHandler$Companion.onLostFocusDoWork(OSFocusHandler.kt:144)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
com.onesignal.OSFocusHandler$OnLostFocusWorker.doWork(OSFocusHandler.kt:123)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	at 
androidx.work.Worker$1.run(Worker.java:86)
2023/03/17 12:44:26.145 22309 22328 Error WM-WorkerWrapper 	... 3 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @Arikaton thank you for the report!  From the log It looks like the SDK is detecting the app has lost focus, and we have not yet initialized `appContext` via `OneSignal.initWithContext` (exception happens [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/d3fda998e7e6c0d99f1bfdc502a308e26c42d91b/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSUtils.java#L275), expected initialization is [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/d3fda998e7e6c0d99f1bfdc502a308e26c42d91b/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L757)).

I haven't been able to drive this myself. Are you able to show where/how you initialize the Unity OneSignal SDK?  If you could provide more logging, specifically around that initialization time, that would also help.

Thanks!

**Comment by emawby** [comment]
Closing for now feel free to reopen if you have any additional details!

**Comment by shefich** [comment]
Stacktraces from Unity's Android Logcat:

```
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper Work [ id=d7a6bda3-0c99-4ace-931d-e8c9098d8e5f, tags={ FOCUS_LOST_WORKER_TAG, com.onesignal.OSFocusHandler$OnLostFocusWorker } ] failed because it threw an exception/error
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at java.lang.Thread.run(Thread.java:1012)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSUtils.packageInstalledAndEnabled(OSUtils.java:275)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSUtils.isGMSInstalledAndEnabled(OSUtils.java:288)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSUtils.supportsGooglePush(OSUtils.java:330)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSUtils.isAndroidDeviceType(OSUtils.java:371)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.LocationController.isGooglePlayServicesAvailable(LocationController.java:337)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.LocationController.onFocusChange(LocationController.java:325)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1352)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSFocusHandler$Companion.onLostFocusDoWork(OSFocusHandler.kt:144)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at com.onesignal.OSFocusHandler$OnLostFocusWorker.doWork(OSFocusHandler.kt:123)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	at androidx.work.Worker$1.run(Worker.java:86)
2023.05.31 18:41:11.017 29030 29069 Error WM-WorkerWrapper 	... 3 more
```

The app started at 2023.05.31 18:41:10.800.
Unity 2020.3.48
OneSignal 3.0.10

Code:
```
 IEnumerator Start () {
		yield return new WaitForSeconds(.5f);
		OneSignal.Default.Initialize("xxx-xxx-xxx-xxx-xxx");
		PromptForPush();
		OneSignal.Default.SetLaunchURLsInApp(false);
		isInitialized = true;
    }
```

**Comment by shefich** [comment]
For now happens on every start of the app.

**Comment by shefich** [comment]
Can someone reopen it?
OneSignal Unity SDK 3.0.10, 3.0.11
