### ISSUE TITLE
[Bug]: ActivityThread$H.handleMessage / android.app.RemoteServiceException

### ISSUE THREAD

**Issue by shefich** [OneSignal/OneSignal-Unity-SDK#617]
### What happened?

Couldn't expand RemoteViews for: StatusBarNotification. Crash.

### Steps to reproduce?

```Markdown
1. Install OneSignal SDk for Unity.
2. Probably post a pushnotification from the app(no images, just text for title and body). 
Last time posted a push from the server long time ago for this app. So it isn't the push from the server.
```

### What did you expect to happen?

I expected not to have crashes. I saw such errors on your Github for Android but no fix/workaround for unity.

### Unity version

2021.3.26
2020.3.48

### OneSignal Unity SDK version

4.0.10
3.0.11

### Platform

Android

### Relevant log output

```Shell
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.xxx.xxx: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xxx.xxx user=UserHandle{0} id=1079863058 tag=null key=0|com.xxx.xxx|1079863058|null|10183: Notification(pri=0 contentView=null vibrate=default sound=default tick defaults=0x7 flags=0x11 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1810)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Thanks for reporting your issue

1. Could you provide a stacktrace of all the threads in the crash report?
    * This can help us see if anything is related OneSignal
2. Can you confirm that no other plugins/SDKs in your app were upgraded or added in the same app release?
3. OneSignal has dependencies on Google Play Services, Firebase, and the Android Support Library.
    * Unlikely, but it's possible that one of these versions was updated in your app which is causing an issue.

**Comment by shefich** [comment]
1. Stacktrace attached.
[stacktrace.txt](https://github.com/OneSignal/OneSignal-Unity-SDK/files/11726903/stacktrace.txt)
2. Have this error on several app versions. SDKs there:
Firebase 10.6.0 & 11.1.0
Google Mobile Ads Unity Plugin v7.4.1 & 8.3.0

**Comment by nan-li** [comment]
Apologies this issue has gone stale; this report and SDK version are quite old.

Please open a new issue with updated details if you are still experiencing related issues.
