### ISSUE TITLE
java.lang.ClassNotFoundException: android.support.v4.view.MenuCompat

### ISSUE THREAD

**Issue by Russel1** [OneSignal/OneSignal-Unity-SDK#62]
I get this error log:
```Java
08-31 16:24:05.378: E/OneSignal(12442): Could not find the Android Support Library. Please make sure it has been correctly added to your project.
08-31 16:24:05.378: E/OneSignal(12442): java.lang.ClassNotFoundException: android.support.v4.view.MenuCompat
08-31 16:24:05.378: E/OneSignal(12442): 	at java.lang.Class.classForName(Native Method)
08-31 16:24:05.378: E/OneSignal(12442): 	at java.lang.Class.forName(Class.java:309)
08-31 16:24:05.378: E/OneSignal(12442): 	at java.lang.Class.forName(Class.java:273)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.onesignal.OSUtils.initializationChecker(OSUtils.java:89)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.onesignal.OneSignal.init(OneSignal.java:350)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.onesignal.OneSignalUnityProxy.<init>(OneSignalUnityProxy.java:61)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
08-31 16:24:05.378: E/OneSignal(12442): 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-31 16:24:05.378: E/OneSignal(12442): 	at android.os.Looper.loop(Looper.java:135)
08-31 16:24:05.378: E/OneSignal(12442): 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
08-31 16:24:05.378: E/OneSignal(12442): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.view.MenuCompat" on path: DexPathList[[zip file "/data/app/de.mobileheroes.realmoneyminer-1/base.apk"],nativeLibraryDirectories=[/data/app/de.mobileheroes.realmoneyminer-1/lib/arm, /vendor/lib, /system/lib]]
08-31 16:24:05.378: E/OneSignal(12442): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-31 16:24:05.378: E/OneSignal(12442): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-31 16:24:05.378: E/OneSignal(12442): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-31 16:24:05.378: E/OneSignal(12442): 	... 12 more
08-31 16:24:05.378: E/OneSignal(12442): 	Suppressed: java.lang.ClassNotFoundException: android.support.v4.view.MenuCompat
08-31 16:24:05.378: E/OneSignal(12442): 		at java.lang.Class.classForName(Native Method)
08-31 16:24:05.378: E/OneSignal(12442): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-31 16:24:05.378: E/OneSignal(12442): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-31 16:24:05.378: E/OneSignal(12442): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-31 16:24:05.378: E/OneSignal(12442): 		... 13 more
08-31 16:24:05.378: E/OneSignal(12442): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
But I added "support-v4-25.3.1" to my project. What is here the problem?
I build with newest OneSignal version and per gradle BuildSystem.

Best regards,
Oli

**Comment by Alamgir** [comment]
@Russel1 Have you taken a look at our Unity Troubleshooting guide: https://documentation.onesignal.com/docs/troubleshooting-unity

Let us know if you're unable to resolve the support dependencies.

**Comment by jkasten2** [comment]
Closing due to inactivity, feel free to reply and we can reopen if the above does not help.
