### ISSUE TITLE
[Bug]: com.onesignal.OSUtils.getManifestMetaBundle

### ISSUE THREAD

**Issue by shefich** [OneSignal/OneSignal-Unity-SDK#622]
### What happened?

Samsung Galaxy J1, Android 5.1.1.

### Steps to reproduce?

```Markdown
1. Don't know how to reproduce
```

### What did you expect to happen?

I expected no to see these crashes

### Unity version

2021.2.12 (latest)

### OneSignal Unity SDK version

3.0.10

### Platform

Android

### Relevant log output

```Shell
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:334)
       at com.onesignal.OSUtils.getManifestMetaBundle(OSUtils.java:412)
       at com.onesignal.OSUtils.getManifestMeta(OSUtils.java:431)
       at com.onesignal.OSNotificationController.setupNotificationServiceExtension(OSNotificationController.java:179)
       at com.onesignal.OneSignal.init(OneSignal.java:819)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:737)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1181)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:889)
       at com.onesignal.OneSignal$7.complete(OneSignal.java:1122)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:211)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:156)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
       at java.lang.Thread.run(Thread.java:818)


Caused by android.os.TransactionTooLargeException:
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:496)
       at android.content.pm.IPackageManager$Stub$Proxy.getApplicationInfo(IPackageManager.java:2542)
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:325)
       at com.onesignal.OSUtils.getManifestMetaBundle(OSUtils.java:412)
       at com.onesignal.OSUtils.getManifestMeta(OSUtils.java:431)
       at com.onesignal.OSNotificationController.setupNotificationServiceExtension(OSNotificationController.java:179)
       at com.onesignal.OneSignal.init(OneSignal.java:819)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:737)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1181)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:889)
       at com.onesignal.OneSignal$7.complete(OneSignal.java:1122)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:211)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:156)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
       at java.lang.Thread.run(Thread.java:818)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@shefich Thank you for reporting have you only seen this on issue the Samsung J1? Based on the stack trace it could be an issue with memory on that particular phone

**Comment by shefich** [comment]
@emawby 
Samsungs Galaxy Tab4 10.0, 
Galaxy J7(2016),
Galaxy J3 Pro,
Galaxy J7,
Galaxy J3(2016),
Galaxy J1 (2016),
Galaxy J1 Ace,
Galaxy E5.

Also Sunvov - WindRiver A455.

OS Android 5.1.1, 5.0.2, 6.0.1, 11.

**Comment by nan-li** [comment]
Apologies this issue has gone stale; this report and SDK version are quite old. 

Please open a new issue with updated details if you are still experiencing related issues.
