### ISSUE TITLE
Got double message when send silent notification

### ISSUE THREAD

**Issue by Thaina** [OneSignal/OneSignal-Unity-SDK#64]
I use onesignal notification to send realtime chat. Normally it could send silent push message for my app to handle correctly. But lately I got double message and one empty notification in android (not in iOS)

It seem like it call my handle function 2 times from these lines

```
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:110)
```

```
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:116)
```

This is the full log from android when the client receiving notification

```
09-20 14:02:22.411 3710 4757 D SamsungAlarmManager: Cancel Alarm calling from uid:10018 pid :5216 / op:PendingIntent{20384cb: PendingIntentRecord{4eeba86 com.google.android.gms broadcastIntent}} 
09-20 14:02:22.440 3710 3720 D SamsungAlarmManager: setExact Intent (T:2/F:5/AC:false) 20170920T140622 - CU:10018/CP:5216 
09-20 14:02:22.459 3710 3726 D CompatibilityInfo: mCompatibilityFlags - 0 
09-20 14:02:22.460 3710 3726 D CompatibilityInfo: applicationDensity - 420 
09-20 14:02:22.460 3710 3726 D CompatibilityInfo: applicationScale - 1.0 
09-20 14:02:22.471 30807 30807 E OneSignal: Error saving notification record! 
09-20 14:02:22.471 30807 30807 E OneSignal: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:166) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:114) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.processBundle(NotificationBundleProcessor.java:395) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:110) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:67) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3309) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.app.ActivityThread.-wrap20(ActivityThread.java) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.os.Handler.dispatchMessage(Handler.java:102) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.os.Looper.loop(Looper.java:154) 
09-20 14:02:22.471 30807 30807 E OneSignal: at android.app.ActivityThread.main(ActivityThread.java:6682) 
09-20 14:02:22.471 30807 30807 E OneSignal: at java.lang.reflect.Method.invoke(Native Method) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
09-20 14:02:22.471 30807 30807 E OneSignal: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
09-20 14:02:22.478 3710 7442 D SamsungAlarmManager: Cancel Alarm calling from uid:10018 pid :5216 / op:PendingIntent{df794a8: PendingIntentRecord{784ff82 com.google.android.gms broadcastIntent}} 
09-20 14:02:22.495 30807 32209 I Unity : GameControllerExample:HandleNotificationReceived: 
09-20 14:02:22.495 30807 32209 I Unity : 
09-20 14:02:22.495 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.495 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : displayType: Notification 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : [HandleNotificationReceived] message , additionalData: {"name":"Test","message":"TTTT","type":"chat","chatType":"zone"} 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : Environment.StackTrace : at System.Environment.get_StackTrace() 
09-20 14:02:22.496 30807 32209 I Unity : at OneSignalNotificationManager.HandleNotificationReceived(.OSNotification notification) 
09-20 14:02:22.496 30807 32209 I Unity : at OneSignal.onPushNotificationReceived(System.String jsonString) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : ExtractStackTrace : OneSignalNotificationManager:HandleNotificationReceived(OSNotification) 
09-20 14:02:22.496 30807 32209 I Unity : OneSignal:onPushNotificationReceived(String) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.496 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.496 30807 32209 I Unity : 
09-20 14:02:22.509 4454 4650 D NetworkController.MobileSignalController(0/2): onDataActivity: direction=3 
09-20 14:02:22.509 4742 5020 D EPDG -- [EPDGService]: onDataActivity: direction=3 
09-20 14:02:22.520 3710 3721 D ApplicationPolicy: isStatusBarNotificationAllowedAsUser: packageName = com.Komodo.SoccerSimulatorGame,userId = 0 
09-20 14:02:22.527 30807 30807 E OneSignal: Error saving notification record! 
09-20 14:02:22.527 30807 30807 E OneSignal: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:166) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:90) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:77) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.startGCMService(GcmBroadcastReceiver.java:127) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:116) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:67) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3309) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.app.ActivityThread.-wrap20(ActivityThread.java) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.os.Handler.dispatchMessage(Handler.java:102) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.os.Looper.loop(Looper.java:154) 
09-20 14:02:22.527 30807 30807 E OneSignal: at android.app.ActivityThread.main(ActivityThread.java:6682) 
09-20 14:02:22.527 30807 30807 E OneSignal: at java.lang.reflect.Method.invoke(Native Method) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
09-20 14:02:22.527 30807 30807 E OneSignal: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
09-20 14:02:22.529 30807 32209 I Unity : GameControllerExample:HandleNotificationReceived: 
09-20 14:02:22.529 30807 32209 I Unity : 
09-20 14:02:22.529 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.529 30807 32209 I Unity : 
09-20 14:02:22.529 30807 32209 I Unity : displayType: Notification 
09-20 14:02:22.529 30807 32209 I Unity : 
09-20 14:02:22.529 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.529 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : [HandleNotificationReceived] message , additionalData: {"name":"Test","message":"TTTT","type":"chat","chatType":"zone"} 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : Environment.StackTrace : at System.Environment.get_StackTrace() 
09-20 14:02:22.530 30807 32209 I Unity : at OneSignalNotificationManager.HandleNotificationReceived(.OSNotification notification) 
09-20 14:02:22.530 30807 32209 I Unity : at OneSignal.onPushNotificationReceived(System.String jsonString) 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : ExtractStackTrace : OneSignalNotificationManager:HandleNotificationReceived(OSNotification) 
09-20 14:02:22.530 30807 32209 I Unity : OneSignal:onPushNotificationReceived(String) 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.530 30807 32209 I Unity : (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51) 
09-20 14:02:22.530 30807 32209 I Unity : 
09-20 14:02:22.534 5216 5216 W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.Komodo.SoccerSimulatorGame launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }
```

It seem like this problem actually occur after our project was update many sdk (include onesignal) last month

**Comment by Thaina** [comment]
Suspect problem from android sdk

https://github.com/OneSignal/OneSignal-Android-SDK/commit/75e7c333bf4d3908ba6cc0381fc7e44ab157ea9a#commitcomment-24425047

**Comment by jkasten2** [comment]
@Thaina Sorry for this issue, the issue was introduced in 2.4.0 of this SDK. This version is using version 3.6.0 of the OneSignal native SDK, will be updating to version 3.6.2 which resolves this issue in the next update.

**Comment by Thaina** [comment]
@jkasten2 Thank you but then when we could get this fix?

**Comment by jkasten2** [comment]
@Thaina We just released SDK 2.4.1 which includes a the updated native SDK the fixes the root of this issue.
https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.4.1

**Comment by oliveriobw** [comment]
Seeing this on Android 030901

**Comment by jkasten2** [comment]
@oliveriobw Can you provide a stacktrace like Thina's above? The line number should have changed and will need this to help hunt down your issue.
