### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by twomedia** [OneSignal/OneSignal-Unity-SDK#66]
I have a crash that's effecting a large number of users (1700) relating to One Signal. The stack trace is bellow. Let me know if you need more details.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke direct method 'com.onesignal.OneSignalStateSynchronizer$UserState com.onesignal.OneSignalStateSynchronizer$UserState.deepClone(java.lang.String)' on a null object reference
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$1500(OneSignalStateSynchronizer.java:233)
       at com.onesignal.OneSignalStateSynchronizer.getUserStateForModification(OneSignalStateSynchronizer.java:677)
       at com.onesignal.OneSignalStateSynchronizer.updateLocation(OneSignalStateSynchronizer.java:751)
       at com.onesignal.SyncService$1.complete(SyncService.java:67)
       at com.onesignal.LocationGMS.fireComplete(LocationGMS.java:216)
       at com.onesignal.LocationGMS.receivedLocationPoint(LocationGMS.java:241)
       at com.onesignal.LocationGMS.access$200(LocationGMS.java:56)
       at com.onesignal.LocationGMS$GoogleApiClientListener.onConnected(LocationGMS.java:256)
       at com.google.android.gms.common.internal.zzm.zzq(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzo(Unknown Source)
       at com.google.android.gms.internal.zzaaj.zzvE(Unknown Source)
       at com.google.android.gms.internal.zzaaj.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaan.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzzy.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzj.zzwZ(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zze.zzxa(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by twomedia** [comment]
I believe this has been fixed in the latest release of the Android SDK. I've updated so hopefully I'll see a reduction in the crash reports.
