### ISSUE TITLE
[Bug]: Notification doesn't work on Amazon Kindle Fire HD 10

### ISSUE THREAD

**Issue by excasualdev** [OneSignal/OneSignal-Unity-SDK#664]
### What happened?

After first launch of application device correctly registered in OneSignal dashboard and subscription status comes to "Subscribed" (check mark).
Then I closed the app and try to send test push for this device and nothing happens.
1. Push notification not arrived
2. No any useful logs at this time in logcat
3. User immediately changes his subscription status in OneSignal dashboard to "Not subscribed" (One times it changed to "No push token")
4. No information inside user about sent notification (like in the other user, who received notification), just "No Recent Activity" placeholder.

Also tried do not to close application before send notification and send it in "hidden" application mode - nothing happening. And, of course, I tried to reinstall application hundreds of time.
Also, the same build working correctly on simple android device (Android 9)

Application has been downloaded from Amazon AppStore, LiveAppTesting, not released yet (Is it matter?)
GooglePlayServices not installed

Amazon Client Id, Client Secret, AppKey, MD5 and SHA-256 of signature key has been double-checked.
Notifications are enabled in device settings
Logs in the second launch of application are saying:
`OneSignal.Default.NotificationPermission = true`
`OneSignal.Default.PushSubscriptionState.isSubscribed = true`
`UserId - exists (seems like a valid)`
`PushToken - exists`
`OneSignal.Default.PushSubscriptionState.isPushDisabled = false`

_Some sensitive information in logs has been hidden by "xxxx" symbols. 
There are no useful logs except "Unity, OneSignal, ADM filter"_

### Steps to reproduce?

```Markdown
1. Install application from Amazon AppStore (LiveAppTesting)
2. Launch application to register user in OneSignal dashboard
3. Close application
4. Find this user and try to send him a notification
5. Notification won't arrived, subscription status turns to "Not subscribed"
```

### What did you expect to happen?

Notification receiving correctly

### Unity version

2021.2.13f1

### OneSignal Unity SDK version

3.0.11 (Also tested on 5.0.5 - same problem)

### Platform

Android

### Relevant log output

```Shell
First launch:

2023-11-09 17:13:40.357  1952-2087  Unity                   pid-1952                             I  [OneSignal] OneSignal.Default set to platform SDK OneSignalSDK.OneSignalAndroid. Current version is 3.0.11
                                                                                                    OneSignalSDK.OneSignal:set_Default(OneSignal)
2023-11-09 17:13:46.383  1952-2087  OneSignal               pid-1952                             D  Adding a task to the pending queue with ID: 1
2023-11-09 17:13:46.383  1952-2087  OneSignal               pid-1952                             D  startPendingTasks with task queue quantity: 1
2023-11-09 17:13:46.385  1952-2413  OneSignal               pid-1952                             D  Retrieved IAMs from DB redisplayedInAppMessages: []
2023-11-09 17:13:46.385  1952-2413  OneSignal               pid-1952                             I  Last Pending Task has ran, shutting down
2023-11-09 17:13:46.386  1952-2087  OneSignal               pid-1952                             D  Attempted to clean 6 month old IAM data, but none exists!
2023-11-09 17:13:46.393  1952-2087  OneSignal               pid-1952                             D  OneSignal InAppMessageTracker initInfluencedTypeFromCache: OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2023-11-09 17:13:46.393  1952-2087  OneSignal               pid-1952                             D  OneSignal NotificationTracker initInfluencedTypeFromCache: OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2023-11-09 17:13:46.395  1952-2087  OneSignal               pid-1952                             D  OneSignal getUnattributedUniqueOutcomeEventsSentByChannel: null
2023-11-09 17:13:46.398  1952-2087  OneSignal               pid-1952                             W  appContext set, but please call setAppId(appId) with a valid appId to complete OneSignal init!
2023-11-09 17:13:46.467  1952-2087  OneSignal               pid-1952                             V  setAppId called with id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx changing id from: null
2023-11-09 17:13:46.467  1952-2087  OneSignal               pid-1952                             V  Starting OneSignal initialization!
2023-11-09 17:13:46.468  1952-2087  OneSignal               pid-1952                             V  No class found, not setting up OSRemoteNotificationReceivedHandler
2023-11-09 17:13:46.468  1952-2087  OneSignal               pid-1952                             V  OneSignal SDK initialization delayed, waiting for remote params.
2023-11-09 17:13:46.471  1952-2087  OneSignal               pid-1952                             D  Starting request to get Android parameters.
2023-11-09 17:13:46.474  1952-2087  OneSignal               pid-1952                             E  Waiting for remote params. Moving clearOneSignalNotifications() operation to a pending queue.
2023-11-09 17:13:46.474  1952-2087  OneSignal               pid-1952                             D  Adding a task to the pending queue with ID: 1
2023-11-09 17:13:46.475  1952-2419  OneSignal               pid-1952                             D  OneSignalRestClient: Making request to: https://api.onesignal.com/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/android_params.js
2023-11-09 17:13:46.496  1952-2087  Unity                   pid-1952                             I  [OneSignal] just init. Permissions: Authorized.IsSubscribed: False. UserId: . PushToken: . PushDisabled: False.
2023-11-09 17:13:46.500  1952-2087  Unity                   pid-1952                             I  [OneSignal] DeviceName: Fire Tablet Model: Amazon KFTRWI. IsAmazon: True
2023-11-09 17:13:46.505  1952-2087  Unity                   pid-1952                             I  [OneSignal] SDK version: 28, current status: Authorized. IsAmazon: True
2023-11-09 17:13:46.509  1952-2087  OneSignal               pid-1952                             E  Waiting for remote params. Moving setExternalUserId() operation to a pending task queue.
2023-11-09 17:13:46.515  1952-2087  OneSignal               pid-1952                             D  Adding a task to the pending queue with ID: 2
2023-11-09 17:13:46.516  1952-2087  OneSignal               pid-1952                             E  Waiting for remote params. Moving setSubscription() operation to a pending queue.
2023-11-09 17:13:46.517  1952-2087  OneSignal               pid-1952                             D  Adding a task to the pending queue with ID: 3
2023-11-09 17:13:46.558  1952-2419  OneSignal               pid-1952                             V  OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/android_params.js
2023-11-09 17:13:46.558  1952-2419  OneSignal               pid-1952                             D  OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/android_params.js
2023-11-09 17:13:46.563  1952-2419  OneSignal               pid-1952                             D  OneSignalRestClient: GET RECEIVED JSON: {"awl_list":{},"android_sender_id":"xxxxxxxxxxxx","chnl_lst":[{"chnl":{"id":"OS_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1","nm":"Game Notifications","dscr":"","grp_id":"OS_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","grp_nm":"Notifications"},"vis":1,"pri":"8"}],"enterp":true,"fba":true,"outcomes":{"direct":{"enabled":true},"indirect":{"notification_attribution":{"minutes_since_displayed":60,"limit":10},"enabled":true},"unattributed":{"enabled":true}},"receive_receipts_enable":true}
2023-11-09 17:13:46.563  1952-2419  OneSignal               pid-1952                             D  OneSignalRestClient: Response has etag of W/"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" so caching the response.
2023-11-09 17:13:46.566  1952-2425  OneSignal               pid-1952                             D  OneSignal saveInfluenceParams: InfluenceParams{indirectNotificationAttributionWindow=60, notificationLimit=10, indirectIAMAttributionWindow=1440, iamLimit=10, directEnabled=true, indirectEnabled=true, unattributedEnabled=true}
2023-11-09 17:13:46.567  1952-2425  OneSignal               pid-1952                             D  reassignDelayedInitParams with appContext: com.safedk.android.SafeDKApplication@85f3886
2023-11-09 17:13:46.567  1952-2425  OneSignal               pid-1952                             V  setAppId called with id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx changing id from: null
2023-11-09 17:13:46.567  1952-2425  OneSignal               pid-1952                             V  Starting OneSignal initialization!
2023-11-09 17:13:46.568  1952-2425  OneSignal               pid-1952                             V  No class found, not setting up OSRemoteNotificationReceivedHandler
2023-11-09 17:13:46.570  1952-2425  OneSignal               pid-1952                             D  OneSignal handleActivityLifecycleHandler inForeground: true
2023-11-09 17:13:46.602  1952-2425  OneSignal               pid-1952                             D  Application foregrounded focus time: 213296919
2023-11-09 17:13:46.603  1952-2425  OneSignal               pid-1952                             D  App id set for first time:  xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:13:46.609  1952-2425  OneSignal               pid-1952                             D  isPastOnSessionTime currentTimeMillis: 1699542826609 lastSessionTime: -31000 difference: 1699542857609
2023-11-09 17:13:46.609  1952-2425  OneSignal               pid-1952                             D  Starting new session with appEntryState: APP_CLOSE
2023-11-09 17:13:46.610  1952-2425  OneSignal               pid-1952                             D  OneSignal cleanOutcomes for session
2023-11-09 17:13:46.610  1952-2425  OneSignal               pid-1952                             D  OneSignal save unattributedUniqueOutcomeEvents: []
2023-11-09 17:13:46.611  1952-2425  OneSignal               pid-1952                             D  OneSignal SessionManager restartSessionIfNeeded with entryAction: APP_CLOSE
2023-11-09 17:13:46.611  1952-2425  OneSignal               pid-1952                             D  OneSignal SessionManager sendSessionEndingWithInfluences with influences: []
2023-11-09 17:13:46.611  1952-2425  OneSignal               pid-1952                             D  Last session time set to: 1699542826611
2023-11-09 17:13:46.611  1952-2425  OneSignal               pid-1952                             D  initWithCachedInAppMessages: null
2023-11-09 17:13:46.612  1952-2425  OneSignal               pid-1952                             I  Location permissions not added on AndroidManifest file
2023-11-09 17:13:46.613  1952-2425  OneSignal               pid-1952                             D  LocationController sendAndClearPromptHandlers from non prompt flow
2023-11-09 17:13:46.613  1952-2425  OneSignal               pid-1952                             D  registerUser:registerForPushFired:false, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@1665150, appId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:13:46.613  1952-2425  OneSignal               pid-1952                             D  registerUser not possible
2023-11-09 17:13:46.615  1952-2425  OneSignal               pid-1952                             V  OneSignal SDK initialization done.
2023-11-09 17:13:46.616  1952-2425  OneSignal               pid-1952                             D  startPendingTasks with task queue quantity: 3
2023-11-09 17:13:46.616  1952-2428  ADM                     pid-1952                             I  Retrieving the registration id.
2023-11-09 17:13:46.617  1952-2431  OneSignal               pid-1952                             D  Running clearOneSignalNotifications() operation from pending queue.
2023-11-09 17:13:46.618  1952-2425  OneSignal               pid-1952                             V  Creating notification channel with channel:
2023-11-09 17:13:46.619  1952-2431  OneSignal               pid-1952                             D  Running setExternalUserId() operation from pending task queue.
2023-11-09 17:13:46.619  1952-2431  OneSignal               pid-1952                             D  Running setSubscription() operation from pending queue.
2023-11-09 17:13:46.619  1952-2431  OneSignal               pid-1952                             I  Last Pending Task has ran, shutting down
2023-11-09 17:13:46.795  1952-2433  OneSignal               pid-1952                             I  Restoring notifications
2023-11-09 17:13:46.796  1952-2433  OneSignal               pid-1952                             I  Querying DB for notifications to restore: created_time > 1698938026 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1699542826
2023-11-09 17:13:46.802  1952-2083  WM-WorkerWrapper        pid-1952                             I  Worker result SUCCESS for Work [ id=6b5a07be-9144-485b-9c67-4df0d7a616ab, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]
2023-11-09 17:13:47.040 30441-31509 ADMRegistrationProvider pid-30441                            I  [ADMRegistrationProvider]Invalid cached result: First install time has changed from 1699527052744 to 1699542788691 for package xxx.xxx.xxx.xxx.xxx
2023-11-09 17:13:47.092 30441-2452  ReceiverChecker         pid-30441                            I  Found Receiver: com.onesignal.ADMMessageHandler$Receiver with action: com.amazon.device.messaging.intent.REGISTRATION
2023-11-09 17:13:47.093 30441-2452  ReceiverChecker         pid-30441                            I  Found Receiver: com.onesignal.ADMMessageHandler$Receiver with action: com.amazon.device.messaging.intent.RECEIVE
2023-11-09 17:13:47.136 30441-2452  ADM                     pid-30441                            I  [ADM][Register]Invalid cached result: First install time has changed from 1699527052744 to 1699542788691 for package xxx.xxx.xxx.xxx.xxx
2023-11-09 17:13:47.136 30441-2452  ADM                     pid-30441                            I  [ADM][Register]Request to register package xxx.xxx.xxx.xxx.xxx due to AppInitiated
2023-11-09 17:13:48.528 30441-2452  ADM                     pid-30441                            I  [ADM][Register]Successfully registered package xxx.xxx.xxx.xxx.xxx. RegistrationId is 'amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx'
2023-11-09 17:13:48.589  1952-1952  OneSignal               pid-1952                             D  ADM latest available: true
2023-11-09 17:13:48.616  1952-2057  OneSignal               pid-1952                             I  ADM registration ID: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx
2023-11-09 17:13:48.618  1952-2057  OneSignal               pid-1952                             D  registerForPushToken completed with id: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx status: 1
2023-11-09 17:13:48.621  1952-2057  OneSignal               pid-1952                             D  registerUser:registerForPushFired:true, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@1665150, appId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:13:48.630  1952-2462  Unity                   pid-1952                             I  [OneSignal] Push subscription state changed. Current: OneSignalSDK.PushSubscriptionState, previous: OneSignalSDK.PushSubscriptionState
2023-11-09 17:13:48.653  1952-2463  OneSignal               pid-1952                             D  registerUserTask calling readyToUpdate
2023-11-09 17:13:50.986  1952-2087  Unity                   pid-1952                             I  [OneSignal] Init(3000 delay). Permissions: Authorized.IsSubscribed: False. UserId: . PushToken: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx. PushDisabled: False.







Second launch:
2023-11-09 17:18:30.847  3287-3792  Unity                   pid-3287                             I  [OneSignal] OneSignal.Default set to platform SDK OneSignalSDK.OneSignalAndroid. Current version is 3.0.11
                                                                                                    OneSignalSDK.OneSignal:set_Default(OneSignal)
2023-11-09 17:18:34.777  3287-3792  OneSignal               pid-3287                             D  Adding a task to the pending queue with ID: 1
2023-11-09 17:18:34.777  3287-3792  OneSignal               pid-3287                             D  startPendingTasks with task queue quantity: 1
2023-11-09 17:18:34.779  3287-3792  OneSignal               pid-3287                             D  Attempted to clean 6 month old IAM data, but none exists!
2023-11-09 17:18:34.780  3287-4066  OneSignal               pid-3287                             D  Retrieved IAMs from DB redisplayedInAppMessages: []
2023-11-09 17:18:34.780  3287-4066  OneSignal               pid-3287                             I  Last Pending Task has ran, shutting down
2023-11-09 17:18:34.781  3287-3792  OneSignal               pid-3287                             D  OneSignal InAppMessageTracker initInfluencedTypeFromCache: OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2023-11-09 17:18:34.782  3287-3792  OneSignal               pid-3287                             D  OneSignal NotificationTracker initInfluencedTypeFromCache: OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2023-11-09 17:18:34.782  3287-3792  OneSignal               pid-3287                             D  OneSignal getUnattributedUniqueOutcomeEventsSentByChannel: []
2023-11-09 17:18:34.784  3287-3792  OneSignal               pid-3287                             V  appContext set and cached app id found, calling setAppId with: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:18:34.784  3287-3792  OneSignal               pid-3287                             V  setAppId called with id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx changing id from: null
2023-11-09 17:18:34.784  3287-3792  OneSignal               pid-3287                             V  Starting OneSignal initialization!
2023-11-09 17:18:34.785  3287-3792  OneSignal               pid-3287                             V  No class found, not setting up OSRemoteNotificationReceivedHandler
2023-11-09 17:18:34.786  3287-3792  OneSignal               pid-3287                             V  OneSignal SDK initialization delayed, waiting for remote params.
2023-11-09 17:18:34.786  3287-3792  OneSignal               pid-3287                             D  Starting request to get Android parameters.
2023-11-09 17:18:34.788  3287-4069  OneSignal               pid-3287                             D  OneSignalRestClient: Making request to: https://api.onesignal.com/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/android_params.js?player_id=yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
2023-11-09 17:18:34.789  3287-4069  OneSignal               pid-3287                             D  OneSignalRestClient: Adding header if-none-match: W/"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
2023-11-09 17:18:34.804  3287-3792  OneSignal               pid-3287                             V  setAppId called with id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx changing id from: null
2023-11-09 17:18:34.804  3287-3792  OneSignal               pid-3287                             V  Starting OneSignal initialization!
2023-11-09 17:18:34.804  3287-3792  OneSignal               pid-3287                             V  No class found, not setting up OSRemoteNotificationReceivedHandler
2023-11-09 17:18:34.805  3287-3792  OneSignal               pid-3287                             V  OneSignal SDK initialization delayed, waiting for remote params.
2023-11-09 17:18:34.805  3287-3792  OneSignal               pid-3287                             E  Waiting for remote params. Moving clearOneSignalNotifications() operation to a pending queue.
2023-11-09 17:18:34.805  3287-3792  OneSignal               pid-3287                             D  Adding a task to the pending queue with ID: 2
2023-11-09 17:18:34.811  3287-3792  Unity                   pid-3287                             I  [OneSignal] just init. Permissions: Authorized.IsSubscribed: True. UserId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy. PushToken: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx. PushDisabled: False.
2023-11-09 17:18:34.815  3287-3792  Unity                   pid-3287                             I  [OneSignal] DeviceName: Fire Tablet Model: Amazon KFTRWI. IsAmazon: True
2023-11-09 17:18:34.820  3287-3792  Unity                   pid-3287                             I  [OneSignal] SDK version: 28, current status: Authorized. IsAmazon: True
2023-11-09 17:18:34.825  3287-3792  OneSignal               pid-3287                             E  Waiting for remote params. Moving setExternalUserId() operation to a pending task queue.
2023-11-09 17:18:34.825  3287-3792  OneSignal               pid-3287                             D  Adding a task to the pending queue with ID: 3
2023-11-09 17:18:34.826  3287-3792  OneSignal               pid-3287                             E  Waiting for remote params. Moving setSubscription() operation to a pending queue.
2023-11-09 17:18:34.827  3287-3792  OneSignal               pid-3287                             D  Adding a task to the pending queue with ID: 4
2023-11-09 17:18:34.884  3287-4069  OneSignal               pid-3287                             V  OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/android_params.js?player_id=yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
2023-11-09 17:18:34.884  3287-4069  OneSignal               pid-3287                             D  OneSignalRestClient: GET - Using Cached response due to 304: {"awl_list":{},"android_sender_id":"xxxxxxxxxxxx","chnl_lst":[{"chnl":{"id":"OS_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","nm":"Game Notifications","dscr":"","grp_id":"OS_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","grp_nm":"Notifications"},"vis":1,"pri":"8"}],"enterp":true,"fba":true,"outcomes":{"direct":{"enabled":true},"indirect":{"notification_attribution":{"minutes_since_displayed":60,"limit":10},"enabled":true},"unattributed":{"enabled":true}},"receive_receipts_enable":true}
2023-11-09 17:18:34.886  3287-4075  OneSignal               pid-3287                             D  OneSignal saveInfluenceParams: InfluenceParams{indirectNotificationAttributionWindow=60, notificationLimit=10, indirectIAMAttributionWindow=1440, iamLimit=10, directEnabled=true, indirectEnabled=true, unattributedEnabled=true}
2023-11-09 17:18:34.887  3287-4075  OneSignal               pid-3287                             D  reassignDelayedInitParams with appContext: com.safedk.android.SafeDKApplication@f10af13
2023-11-09 17:18:34.887  3287-4075  OneSignal               pid-3287                             V  setAppId called with id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx changing id from: null
2023-11-09 17:18:34.887  3287-4075  OneSignal               pid-3287                             V  Starting OneSignal initialization!
2023-11-09 17:18:34.887  3287-4075  OneSignal               pid-3287                             V  No class found, not setting up OSRemoteNotificationReceivedHandler
2023-11-09 17:18:34.888  3287-4075  OneSignal               pid-3287                             D  OneSignal handleActivityLifecycleHandler inForeground: true
2023-11-09 17:18:34.890  3287-4075  OneSignal               pid-3287                             D  Application foregrounded focus time: 213585207
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  isPastOnSessionTime currentTimeMillis: 1699543114893 lastSessionTime: 1699543091969 difference: 22924
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  Continue on same session with appEntryState: APP_CLOSE
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  OneSignal SessionManager attemptSessionUpgrade with entryAction: APP_CLOSE
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  OneSignal SessionManager attemptSessionUpgrade try UNATTRIBUTED to INDIRECT upgrade
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  Trackers after update attempt: [OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}, OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  OneSignal SessionManager sendSessionEndingWithInfluences with influences: []
2023-11-09 17:18:34.893  3287-4075  OneSignal               pid-3287                             D  initWithCachedInAppMessages: null
2023-11-09 17:18:34.895  3287-4075  OneSignal               pid-3287                             I  Location permissions not added on AndroidManifest file
2023-11-09 17:18:34.895  3287-4075  OneSignal               pid-3287                             D  LocationController sendAndClearPromptHandlers from non prompt flow
2023-11-09 17:18:34.895  3287-4075  OneSignal               pid-3287                             D  registerUser:registerForPushFired:false, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@62457ee, appId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:18:34.895  3287-4075  OneSignal               pid-3287                             D  registerUser not possible
2023-11-09 17:18:34.896  3287-4075  OneSignal               pid-3287                             V  OneSignal SDK initialization done.
2023-11-09 17:18:34.897  3287-4075  OneSignal               pid-3287                             D  startPendingTasks with task queue quantity: 4
2023-11-09 17:18:34.898  3287-4079  OneSignal               pid-3287                             D  Running onAppLostFocus() operation from a pending task queue.
2023-11-09 17:18:34.898  3287-4077  ADM                     pid-3287                             I  Retrieving the registration id.
2023-11-09 17:18:34.898  3287-4079  OneSignal               pid-3287                             D  Running clearOneSignalNotifications() operation from pending queue.
2023-11-09 17:18:34.899  3287-4075  OneSignal               pid-3287                             V  Creating notification channel with channel:
2023-11-09 17:18:34.903  3287-4079  OneSignal               pid-3287                             D  Running setExternalUserId() operation from pending task queue.
2023-11-09 17:18:34.904  3287-4079  OneSignal               pid-3287                             D  Running setSubscription() operation from pending queue.
2023-11-09 17:18:34.904  3287-4079  OneSignal               pid-3287                             I  Last Pending Task has ran, shutting down
2023-11-09 17:18:34.965  3287-4080  OneSignal               pid-3287                             I  Restoring notifications
2023-11-09 17:18:34.966  3287-4080  OneSignal               pid-3287                             I  Querying DB for notifications to restore: created_time > 1698938314 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1699543114
2023-11-09 17:18:34.970  3287-3352  WM-WorkerWrapper        pid-3287                             I  Worker result SUCCESS for Work [ id=63d7b4ce-fe92-4a8b-8f6d-65d05f58dbc2, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]
2023-11-09 17:18:34.997  3287-4077  OneSignal               pid-3287                             D  ADM Already registered with ID:amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx
2023-11-09 17:18:34.997  3287-4077  OneSignal               pid-3287                             D  registerForPushToken completed with id: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx status: 1
2023-11-09 17:18:34.997  3287-4077  OneSignal               pid-3287                             D  registerUser:registerForPushFired:true, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@62457ee, appId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2023-11-09 17:18:35.001  3287-4083  OneSignal               pid-3287                             D  registerUserTask calling readyToUpdate
2023-11-09 17:18:38.628  3287-3792  Unity                   pid-3287                             I  [OneSignal] Init(3000 delay). Permissions: Authorized.IsSubscribed: True. UserId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy. PushToken: amzn1.adm-registration.v3.xxxxxxxxxxxxxxxxxx. PushDisabled: False.
2023-11-09 17:18:40.272  3287-4076  OneSignal               pid-3287                             D  UserStateSynchronizer internalSyncUserState from session call: true jsonBody: {"app_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
2023-11-09 17:18:40.278  3287-4198  OneSignal               pid-3287                             D  OneSignalRestClient: Making request to: https://api.onesignal.com/players/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy/on_session
2023-11-09 17:18:40.278  3287-4198  OneSignal               pid-3287                             D  OneSignalRestClient: POST SEND JSON: {"app_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
2023-11-09 17:18:40.442  3287-4198  OneSignal               pid-3287                             V  OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy/on_session
2023-11-09 17:18:40.442  3287-4198  OneSignal               pid-3287                             D  OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy/on_session
2023-11-09 17:18:40.444  3287-4198  OneSignal               pid-3287                             D  OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"}
2023-11-09 17:18:40.444  3287-4202  OneSignal               pid-3287                             D  doCreateOrNewSession:response: {"success":true,"id":"yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"}
2023-11-09 17:18:40.446  3287-4202  OneSignal               pid-3287                             I  Device registered, UserId = yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kniewolewski** [comment]
I've got the same issue. 
One additional thing - to make 5.0.5 run on Amazon Fire I had to add manually Amazon SDK library, Without it several seconds after init Onesignal was throwing an error: 

> E  FATAL EXCEPTION: Thread-45
                                                                                                    Process: com.packageName, PID: 27558
                                                                                                    kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
                                                                                                    	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
                                                                                                    	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:501)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                                                                                                    	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@excasualdev could you try re-saving your Amazon setting on the OneSignal dashboard?
![image](https://github.com/OneSignal/OneSignal-Unity-SDK/assets/645861/ed65722f-c024-4b90-aaa2-1274da5ae4c1)

This is a work around that should get you up and running while we investigate the root cause.



@kniewolewski the error you noted may show up if there was an issue connecting to Amazon's servers. You don't have to include the Amazon SDK library in your app.

**Comment by jkasten2** [comment]
@excasualdev Did re-saving the Amazon config, noted above, fix this issue for you?
