### ISSUE TITLE
[Bug]: Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by ajaybirla-fabzen** [OneSignal/OneSignal-Unity-SDK#683]
### What happened?

The application crashes whenever it receives a notification.

### Steps to reproduce?

```Markdown
1. Launch the application.
2. Send a notification to the application.
3. Click on the notification.
4. Observe the application crash.
```

### What did you expect to happen?

I expect the app to not crash whenever it receives a notification.

### Unity version

2021.3.17f1

### OneSignal Unity SDK version

5.0.5

### Platform

Android

### Relevant log output

```Shell
Caused by java.lang.NullPointerException:
       at com.onesignal.core.internal.backend.impl.ParamsBackendService.fetchParams(ParamsBackendService.kt:38)
       at com.onesignal.core.internal.backend.impl.ParamsBackendService$fetchParams$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
       at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:60)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:59)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@ajaybirla-fabzen are you still seeing this issue? It might be related to your OneSignal app id, if you still see it can you try creating a different OneSignal app?

If you narrow it down to a specific OneSignal app id please reach out to OneSignal support and let them so someone there can take a look at your specific app.

**Comment by ajaybirla-fabzen** [comment]
@jkasten2 This issue is not observed anymore after updating to the latest One Signal Unity SDK. Thanks.
