### ISSUE TITLE
[ANR]: com.onesignal.OneSignal$oneSignal$2.invoke ANR issue

### ISSUE THREAD

**Issue by catalin-zambalic-ma** [OneSignal/OneSignal-Unity-SDK#756]
### What happened?

ANR

### Steps to reproduce?

```Markdown
No reproduction steps.
```

### What did you expect to happen?

No ANR encountered.

### OneSignal Android SDK version

Unity OneSignal Android SDK v5.1.6

### Android version

12

### Specific Android models

```Markdown
Xiaomi Poco C50
```

### Relevant log output

```Shell
main (runnable):tid=1 systid=20940 
       at com.onesignal.OneSignal$oneSignal$2.invoke(OneSignal.kt:196)
       at com.onesignal.OneSignal$oneSignal$2.invoke(OneSignal.kt:195)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.onesignal.OneSignal.getOneSignal(OneSignal.kt:195)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:208)
       at com.onesignal.notifications.receivers.FCMBroadcastReceiver.onReceive(FCMBroadcastReceiver.kt:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4348)
       at android.app.ActivityThread.access$1700(ActivityThread.java:253)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2101)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@catalin-zambalic-ma we fixed a number of ANRs in the [OneSignal-Unity-SDK 5.1.8 release](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/5.1.8). Can you try it out a let us know if it fully resolves this specific ANR?
