### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Arodus** [OneSignal/OneSignal-Unity-SDK#8]
I still get this [Issue](https://github.com/OneSignal/OneSignal-Android-SDK/issues/49) in the current UnitySDK.

    Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
       at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
       at com.onesignal.OneSignalStateSynchronizer.generateJsonDiff(OneSignalStateSynchronizer.java:75)
       at com.onesignal.OneSignalStateSynchronizer.access$200(OneSignalStateSynchronizer.java:46)
       at com.onesignal.OneSignalStateSynchronizer$UserState.generateJsonDiff(OneSignalStateSynchronizer.java:261)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$600(OneSignalStateSynchronizer.java:201)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:474)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:438)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jkasten2** [comment]
@Arodus A few more occurrences of this error was fixed in version 3.0.3 of the native SDK used by this plugin. See https://github.com/OneSignal/OneSignal-Android-SDK/issues/88

We will be updating the Unity SDK to new OneSignal native Android 3.0 and iOS 2.0 SDKs in the next few weeks.

**Comment by alamboley** [comment]
Any news on this? Seeing this issue prevent me from integrating the current SDK to try OneSignal :p

**Comment by jkasten2** [comment]
@alamboley This error is a rare race condition. We have only seen a few apps report of this `ConcurrentModificationException` error across all our SDKs.

We don't have an exact date for you on the release, there are a number of improvements we are bring to the Unity 2.0 SDK.

**Comment by jkasten2** [comment]
@Arodus @alamboley Our [2.0.0 SDK](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.0.0) is release and contains our 3.2.0 native java sdk.

See the new setup instructions below.
https://documentation.onesignal.com/docs/installing-the-onesignal-sdk
