### ISSUE TITLE
Crash on Samsung devices

### ISSUE THREAD

**Issue by AnnKryvenko** [OneSignal/OneSignal-Unity-SDK#83]
![screen shot 2018-02-06 at 22 47 14](https://user-images.githubusercontent.com/16333229/35883389-c6a7b296-0b8f-11e8-8190-c776b58f5b17.png)
Unity version: 2017.3.0p2
OneSignal-Unity-SDK version: 2.5.0

```java
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.dontblinkgames.merchmania: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.dontblinkgames.merchmania user=UserHandle{0} id=2076425911 tag=null key=0|com.dontblinkgames.merchmania|2076425911|null|10228: Notification(pri=-1 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by hakansaglam** [comment]
Is there any plan on this issue?

**Comment by jkasten2** [comment]
@AnnKryvenko @hakansaglam The OneSignal Android Native 3.8.2 SDK noted in that thread will be included in the next Unity SDK update.

**Comment by jkasten2** [comment]
The [OneSignal Unity SDK 2.6.3](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.3) has been released with this possible fix. Let us know the results after you release an update to your app. Thanks!

**Comment by Nightsd01** [comment]
Closing due to inactivity, I assume this fixed your issue. If not please feel free to respond and I'll be happy to reopen and investigate.

**Comment by hakansaglam** [comment]
It seems that related fix is not worked:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263
