### ISSUE TITLE
java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy when using Gradle build system with Proguard

### ISSUE THREAD

**Issue by kaninhot004** [OneSignal/OneSignal-Unity-SDK#86]
```java
<i>AndroidPlayer(WIKO_View@192.168.1.47)</i>
AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at java.lang.Class.forName(Class.java:326)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.c(Unknown Source)
	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.TinnoLoop(Looper.java:138)
	at android.os.Looper.loop(Looper.java:208)
	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignalUnityProxy" on path: DexPathList[[zip file "/data/app/com.ferretking.eliving-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ferretking.eliving-1/lib/arm, /data/app/com.ferretking.eliving-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more
  at UnityEngine.AndroidJNISafe.CheckException () [0x0008c] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:24 
  at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs:207 
  at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x002d8] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:460 
  at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00004] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/AndroidJavaBindings.gen.cs:82 
  at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x0001e] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:591 
  at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00021] in /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:193 
  at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x0000a] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/AndroidJavaBindings.gen.cs:18 
  at OneSignalAndroid..ctor (System.String gameObjectName, System.String googleProjectNumber, System.String appId, OSInFocusDisplayOption displayOption, LOG_LEVEL logLevel, LOG_LEVEL visualLevel) [0x00032] in D:\rm_mobile\Assets\OneSignal\src\OneSignalAndroid.cs:38 
  at OneSignal.initAndroid () [0x00029] in D:\rm_mobile\Assets\OneSignal\src\OneSignal.cs:377 
  at OneSignal.initOneSignalPlatform () [0x0001a] in D:\rm_mobile\Assets\OneSignal\src\OneSignal.cs:357 
  at OneSignal.Init () [0x00001] in D:\rm_mobile\Assets\OneSignal\src\OneSignal.cs:348 
  at OneSignal+UnityBuilder.EndInit () [0x00001] in D:\rm_mobile\Assets\OneSignal\src\OneSignal.cs:303 
  at OneSignalController.Start () [0x0005d] in D:\rm_mobile\Assets\_Script\OneSignal\OneSignalController.cs:21 
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Export/AndroidJNISafe.cs Line: 24)


```

Anyone had this issue? Thank you!

**Comment by Nightsd01** [comment]
@kaninhot004 Are you certain you followed every step of the [setup guide](https://documentation.onesignal.com/docs/unity-sdk-setup) correctly?

**Comment by kaninhot004** [comment]
Yes sure I follow every step and troubleshooting.

I will try not to click Assets > Play Services Resolver > Android Resolver > Resolve today thanks!!

**Comment by Nightsd01** [comment]
@kaninhot004 I am not sure what you mean. Are you saying the Android resolver fixed your issue?

**Comment by kaninhot004** [comment]
Sorry for bad English.
- I've followed the One Signal Guide.
- I've google for 2 days.

Still error maybe Gradle & Proguard Build is cause of this. ( I can't build Internal I've 3-4 plugin in Unity Project )

**Comment by georgepiva** [comment]
Hi @kaninhot004!
I am facing the same issue here.
Any update on this subject?

**Comment by jkasten2** [comment]
We released [version 2.6.3](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.3) yesterday, can you try this version to see if it resolves this issue?

If not, let us know what "Build System" you used (Internal, Gradle, or ADT) and if you used proguard

**Comment by georgepiva** [comment]
Hi @jkasten2!
I am going to try the new version right now. I will come back to you.
About the "Build System", I am using Gradle as shown inside the attached image.

![build_settings_and_unity_2017_1_2p1__64bit__-_initialscene_unity_-_redstonemahjong_-_android__opengl_4_1_](https://user-images.githubusercontent.com/791511/37540233-f984d140-2934-11e8-8688-c50db36e22b2.jpg)

**Comment by georgepiva** [comment]
@jkasten2 runtime errors still present:

> 03-16 20:15:49.495 3545-3564/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.google.android.gms.analytics.GoogleAnalytics
>                                         java.lang.ClassNotFoundException: com.google.android.gms.analytics.GoogleAnalytics
>                                             at java.lang.Class.classForName(Native Method)
>                                             at java.lang.Class.forName(Class.java:400)
>                                             at java.lang.Class.forName(Class.java:326)
>                                             at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
>                                             at com.unity3d.player.UnityPlayer.c(Unknown Source)
>                                             at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
>                                             at android.os.Handler.dispatchMessage(Handler.java:98)
>                                             at android.os.Looper.loop(Looper.java:154)
>                                             at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
>                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.analytics.GoogleAnalytics" on path: DexPathList[[zip file "/data/app/mobi.redstonegames.redstonemahjong-1/base.apk"],nativeLibraryDirectories=[/data/app/mobi.redstonegames.redstonemahjong-1/lib/x86, /data/app/mobi.redstonegames.redstonemahjong-1/base.apk!/lib/x86, /syst
> 03-16 20:15:50.523 3545-3564/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
>                                         java.lang.ClassNotFoundException: com.onesignal.OneSignalUnityProxy
>                                             at java.lang.Class.classForName(Native Method)
>                                             at java.lang.Class.forName(Class.java:400)
>                                             at java.lang.Class.forName(Class.java:326)
>                                             at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
>                                             at com.unity3d.player.UnityPlayer.c(Unknown Source)
>                                             at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
>                                             at android.os.Handler.dispatchMessage(Handler.java:98)
>                                             at android.os.Looper.loop(Looper.java:154)
>                                             at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
>                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignalUnityProxy" on path: DexPathList[[zip file "/data/app/mobi.redstonegames.redstonemahjong-1/base.apk"],nativeLibraryDirectories=[/data/app/mobi.redstonegames.redstonemahjong-1/lib/x86, /data/app/mobi.redstonegames.redstonemahjong-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
>                                         	at dalvik.system.BaseD

In order to allow Gradle to build the APK, I needed to do the next workaround:

https://answers.unity.com/questions/1479800/commandinvokationfailure-gradle-build-failed-with.html

May this be the reason of this issue?

**Comment by jkasten2** [comment]
Thanks for the details, I was able to reproduce the problem but only when selecting Gradle as a "Build System". It defaults "Minify" to Proguard which ends up removing the required  `com.onesignal.OneSignalUnityProxy` class. If you need to use the Gradle build system you can turn this off to work around the issue for now.

![image](https://user-images.githubusercontent.com/645861/37548932-c2a8a40e-2938-11e8-82d1-3dccf2537fc9.png)

Another option if you need to keep Proguard is to check "User Proguard File" and add the following file to the `Assets/Plugins/Android/proguard-user.txt` file it creates.
```java
-keep class com.onesignal.OneSignalUnityProxy {*;}
```

We will see what we can do in the next update to make this automatically

**Comment by jkasten2** [comment]
The proguard rule is now added automatically in [version 2.6.4](https://github.com/OneSignal/OneSignal-Unity-SDK/releases/tag/2.6.4) to fix this issue
